/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EVPEmployee service. Represents a row in the &quot;EVPEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.evp.model.impl.EVPEmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.evp.model.impl.EVPEmployeeImpl}.
 * </p>
 *
 * @author Val Nagy
 * @see EVPEmployee
 * @see com.liferay.evp.model.impl.EVPEmployeeImpl
 * @see com.liferay.evp.model.impl.EVPEmployeeModelImpl
 * @generated
 */
public interface EVPEmployeeModel extends AuditedModel, BaseModel<EVPEmployee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e v p employee model instance should use the {@link EVPEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this e v p employee.
	 *
	 * @return the primary key of this e v p employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e v p employee.
	 *
	 * @param primaryKey the primary key of this e v p employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evp employee ID of this e v p employee.
	 *
	 * @return the evp employee ID of this e v p employee
	 */
	public long getEvpEmployeeId();

	/**
	 * Sets the evp employee ID of this e v p employee.
	 *
	 * @param evpEmployeeId the evp employee ID of this e v p employee
	 */
	public void setEvpEmployeeId(long evpEmployeeId);

	/**
	 * Returns the company ID of this e v p employee.
	 *
	 * @return the company ID of this e v p employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e v p employee.
	 *
	 * @param companyId the company ID of this e v p employee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e v p employee.
	 *
	 * @return the user ID of this e v p employee
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e v p employee.
	 *
	 * @param userId the user ID of this e v p employee
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e v p employee.
	 *
	 * @return the user uuid of this e v p employee
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e v p employee.
	 *
	 * @param userUuid the user uuid of this e v p employee
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e v p employee.
	 *
	 * @return the user name of this e v p employee
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e v p employee.
	 *
	 * @param userName the user name of this e v p employee
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e v p employee.
	 *
	 * @return the create date of this e v p employee
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e v p employee.
	 *
	 * @param createDate the create date of this e v p employee
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e v p employee.
	 *
	 * @return the modified date of this e v p employee
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e v p employee.
	 *
	 * @param modifiedDate the modified date of this e v p employee
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee user ID of this e v p employee.
	 *
	 * @return the employee user ID of this e v p employee
	 */
	public long getEmployeeUserId();

	/**
	 * Sets the employee user ID of this e v p employee.
	 *
	 * @param employeeUserId the employee user ID of this e v p employee
	 */
	public void setEmployeeUserId(long employeeUserId);

	/**
	 * Returns the employee user uuid of this e v p employee.
	 *
	 * @return the employee user uuid of this e v p employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getEmployeeUserUuid() throws SystemException;

	/**
	 * Sets the employee user uuid of this e v p employee.
	 *
	 * @param employeeUserUuid the employee user uuid of this e v p employee
	 */
	public void setEmployeeUserUuid(String employeeUserUuid);

	/**
	 * Returns the manager user ID of this e v p employee.
	 *
	 * @return the manager user ID of this e v p employee
	 */
	public long getManagerUserId();

	/**
	 * Sets the manager user ID of this e v p employee.
	 *
	 * @param managerUserId the manager user ID of this e v p employee
	 */
	public void setManagerUserId(long managerUserId);

	/**
	 * Returns the manager user uuid of this e v p employee.
	 *
	 * @return the manager user uuid of this e v p employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getManagerUserUuid() throws SystemException;

	/**
	 * Sets the manager user uuid of this e v p employee.
	 *
	 * @param managerUserUuid the manager user uuid of this e v p employee
	 */
	public void setManagerUserUuid(String managerUserUuid);

	/**
	 * Returns the subsidiary e v p division ID of this e v p employee.
	 *
	 * @return the subsidiary e v p division ID of this e v p employee
	 */
	public long getSubsidiaryEVPDivisionId();

	/**
	 * Sets the subsidiary e v p division ID of this e v p employee.
	 *
	 * @param subsidiaryEVPDivisionId the subsidiary e v p division ID of this e v p employee
	 */
	public void setSubsidiaryEVPDivisionId(long subsidiaryEVPDivisionId);

	/**
	 * Returns the employment type of this e v p employee.
	 *
	 * @return the employment type of this e v p employee
	 */
	public int getEmploymentType();

	/**
	 * Sets the employment type of this e v p employee.
	 *
	 * @param employmentType the employment type of this e v p employee
	 */
	public void setEmploymentType(int employmentType);

	/**
	 * Returns the hire date of this e v p employee.
	 *
	 * @return the hire date of this e v p employee
	 */
	public Date getHireDate();

	/**
	 * Sets the hire date of this e v p employee.
	 *
	 * @param hireDate the hire date of this e v p employee
	 */
	public void setHireDate(Date hireDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.evp.model.EVPEmployee evpEmployee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.evp.model.EVPEmployee> toCacheModel();

	@Override
	public com.liferay.evp.model.EVPEmployee toEscapedModel();

	@Override
	public com.liferay.evp.model.EVPEmployee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}