/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EVPGrantRequest service. Represents a row in the &quot;EVPGrantRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.evp.model.impl.EVPGrantRequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.evp.model.impl.EVPGrantRequestImpl}.
 * </p>
 *
 * @author Val Nagy
 * @see EVPGrantRequest
 * @see com.liferay.evp.model.impl.EVPGrantRequestImpl
 * @see com.liferay.evp.model.impl.EVPGrantRequestModelImpl
 * @generated
 */
public interface EVPGrantRequestModel extends AuditedModel,
	BaseModel<EVPGrantRequest>, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e v p grant request model instance should use the {@link EVPGrantRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this e v p grant request.
	 *
	 * @return the primary key of this e v p grant request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e v p grant request.
	 *
	 * @param primaryKey the primary key of this e v p grant request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evp grant request ID of this e v p grant request.
	 *
	 * @return the evp grant request ID of this e v p grant request
	 */
	public long getEvpGrantRequestId();

	/**
	 * Sets the evp grant request ID of this e v p grant request.
	 *
	 * @param evpGrantRequestId the evp grant request ID of this e v p grant request
	 */
	public void setEvpGrantRequestId(long evpGrantRequestId);

	/**
	 * Returns the company ID of this e v p grant request.
	 *
	 * @return the company ID of this e v p grant request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e v p grant request.
	 *
	 * @param companyId the company ID of this e v p grant request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e v p grant request.
	 *
	 * @return the user ID of this e v p grant request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e v p grant request.
	 *
	 * @param userId the user ID of this e v p grant request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e v p grant request.
	 *
	 * @return the user uuid of this e v p grant request
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e v p grant request.
	 *
	 * @param userUuid the user uuid of this e v p grant request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e v p grant request.
	 *
	 * @return the user name of this e v p grant request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e v p grant request.
	 *
	 * @param userName the user name of this e v p grant request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e v p grant request.
	 *
	 * @return the create date of this e v p grant request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e v p grant request.
	 *
	 * @param createDate the create date of this e v p grant request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e v p grant request.
	 *
	 * @return the modified date of this e v p grant request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e v p grant request.
	 *
	 * @param modifiedDate the modified date of this e v p grant request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the contact email address ID of this e v p grant request.
	 *
	 * @return the contact email address ID of this e v p grant request
	 */
	public long getContactEmailAddressId();

	/**
	 * Sets the contact email address ID of this e v p grant request.
	 *
	 * @param contactEmailAddressId the contact email address ID of this e v p grant request
	 */
	public void setContactEmailAddressId(long contactEmailAddressId);

	/**
	 * Returns the contact phone ID of this e v p grant request.
	 *
	 * @return the contact phone ID of this e v p grant request
	 */
	public long getContactPhoneId();

	/**
	 * Sets the contact phone ID of this e v p grant request.
	 *
	 * @param contactPhoneId the contact phone ID of this e v p grant request
	 */
	public void setContactPhoneId(long contactPhoneId);

	/**
	 * Returns the contact user ID of this e v p grant request.
	 *
	 * @return the contact user ID of this e v p grant request
	 */
	public long getContactUserId();

	/**
	 * Sets the contact user ID of this e v p grant request.
	 *
	 * @param contactUserId the contact user ID of this e v p grant request
	 */
	public void setContactUserId(long contactUserId);

	/**
	 * Returns the contact user uuid of this e v p grant request.
	 *
	 * @return the contact user uuid of this e v p grant request
	 * @throws SystemException if a system exception occurred
	 */
	public String getContactUserUuid() throws SystemException;

	/**
	 * Sets the contact user uuid of this e v p grant request.
	 *
	 * @param contactUserUuid the contact user uuid of this e v p grant request
	 */
	public void setContactUserUuid(String contactUserUuid);

	/**
	 * Returns the evp request organization ID of this e v p grant request.
	 *
	 * @return the evp request organization ID of this e v p grant request
	 */
	public long getEvpRequestOrganizationId();

	/**
	 * Sets the evp request organization ID of this e v p grant request.
	 *
	 * @param evpRequestOrganizationId the evp request organization ID of this e v p grant request
	 */
	public void setEvpRequestOrganizationId(long evpRequestOrganizationId);

	/**
	 * Returns the parent e v p grant request ID of this e v p grant request.
	 *
	 * @return the parent e v p grant request ID of this e v p grant request
	 */
	public long getParentEVPGrantRequestId();

	/**
	 * Sets the parent e v p grant request ID of this e v p grant request.
	 *
	 * @param parentEVPGrantRequestId the parent e v p grant request ID of this e v p grant request
	 */
	public void setParentEVPGrantRequestId(long parentEVPGrantRequestId);

	/**
	 * Returns the request organization address ID of this e v p grant request.
	 *
	 * @return the request organization address ID of this e v p grant request
	 */
	public long getRequestOrganizationAddressId();

	/**
	 * Sets the request organization address ID of this e v p grant request.
	 *
	 * @param requestOrganizationAddressId the request organization address ID of this e v p grant request
	 */
	public void setRequestOrganizationAddressId(
		long requestOrganizationAddressId);

	/**
	 * Returns the request organization website ID of this e v p grant request.
	 *
	 * @return the request organization website ID of this e v p grant request
	 */
	public long getRequestOrganizationWebsiteId();

	/**
	 * Sets the request organization website ID of this e v p grant request.
	 *
	 * @param requestOrganizationWebsiteId the request organization website ID of this e v p grant request
	 */
	public void setRequestOrganizationWebsiteId(
		long requestOrganizationWebsiteId);

	/**
	 * Returns the subsidiary group ID of this e v p grant request.
	 *
	 * @return the subsidiary group ID of this e v p grant request
	 */
	public long getSubsidiaryGroupId();

	/**
	 * Sets the subsidiary group ID of this e v p grant request.
	 *
	 * @param subsidiaryGroupId the subsidiary group ID of this e v p grant request
	 */
	public void setSubsidiaryGroupId(long subsidiaryGroupId);

	/**
	 * Returns the description of this e v p grant request.
	 *
	 * @return the description of this e v p grant request
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e v p grant request.
	 *
	 * @param description the description of this e v p grant request
	 */
	public void setDescription(String description);

	/**
	 * Returns the employment type of this e v p grant request.
	 *
	 * @return the employment type of this e v p grant request
	 */
	public int getEmploymentType();

	/**
	 * Sets the employment type of this e v p grant request.
	 *
	 * @param employmentType the employment type of this e v p grant request
	 */
	public void setEmploymentType(int employmentType);

	/**
	 * Returns the employment hours per week of this e v p grant request.
	 *
	 * @return the employment hours per week of this e v p grant request
	 */
	public int getEmploymentHoursPerWeek();

	/**
	 * Sets the employment hours per week of this e v p grant request.
	 *
	 * @param employmentHoursPerWeek the employment hours per week of this e v p grant request
	 */
	public void setEmploymentHoursPerWeek(int employmentHoursPerWeek);

	/**
	 * Returns the purpose of this e v p grant request.
	 *
	 * @return the purpose of this e v p grant request
	 */
	@AutoEscape
	public String getPurpose();

	/**
	 * Sets the purpose of this e v p grant request.
	 *
	 * @param purpose the purpose of this e v p grant request
	 */
	public void setPurpose(String purpose);

	/**
	 * Returns the purpose other of this e v p grant request.
	 *
	 * @return the purpose other of this e v p grant request
	 */
	@AutoEscape
	public String getPurposeOther();

	/**
	 * Sets the purpose other of this e v p grant request.
	 *
	 * @param purposeOther the purpose other of this e v p grant request
	 */
	public void setPurposeOther(String purposeOther);

	/**
	 * Returns the behalf of of this e v p grant request.
	 *
	 * @return the behalf of of this e v p grant request
	 */
	@AutoEscape
	public String getBehalfOf();

	/**
	 * Sets the behalf of of this e v p grant request.
	 *
	 * @param behalfOf the behalf of of this e v p grant request
	 */
	public void setBehalfOf(String behalfOf);

	/**
	 * Returns the behalf of other of this e v p grant request.
	 *
	 * @return the behalf of other of this e v p grant request
	 */
	@AutoEscape
	public String getBehalfOfOther();

	/**
	 * Sets the behalf of other of this e v p grant request.
	 *
	 * @param behalfOfOther the behalf of other of this e v p grant request
	 */
	public void setBehalfOfOther(String behalfOfOther);

	/**
	 * Returns the status of this e v p grant request.
	 *
	 * @return the status of this e v p grant request
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this e v p grant request.
	 *
	 * @param status the status of this e v p grant request
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this e v p grant request.
	 *
	 * @return the status by user ID of this e v p grant request
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this e v p grant request.
	 *
	 * @param statusByUserId the status by user ID of this e v p grant request
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this e v p grant request.
	 *
	 * @return the status by user uuid of this e v p grant request
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this e v p grant request.
	 *
	 * @param statusByUserUuid the status by user uuid of this e v p grant request
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this e v p grant request.
	 *
	 * @return the status by user name of this e v p grant request
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this e v p grant request.
	 *
	 * @param statusByUserName the status by user name of this e v p grant request
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this e v p grant request.
	 *
	 * @return the status date of this e v p grant request
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this e v p grant request.
	 *
	 * @param statusDate the status date of this e v p grant request
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this e v p grant request is approved.
	 *
	 * @return <code>true</code> if this e v p grant request is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this e v p grant request is denied.
	 *
	 * @return <code>true</code> if this e v p grant request is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this e v p grant request is a draft.
	 *
	 * @return <code>true</code> if this e v p grant request is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this e v p grant request is expired.
	 *
	 * @return <code>true</code> if this e v p grant request is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this e v p grant request is inactive.
	 *
	 * @return <code>true</code> if this e v p grant request is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this e v p grant request is incomplete.
	 *
	 * @return <code>true</code> if this e v p grant request is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this e v p grant request is pending.
	 *
	 * @return <code>true</code> if this e v p grant request is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this e v p grant request is scheduled.
	 *
	 * @return <code>true</code> if this e v p grant request is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.evp.model.EVPGrantRequest evpGrantRequest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.evp.model.EVPGrantRequest> toCacheModel();

	@Override
	public com.liferay.evp.model.EVPGrantRequest toEscapedModel();

	@Override
	public com.liferay.evp.model.EVPGrantRequest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}