/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EVPRequestOrganization service. Represents a row in the &quot;EVPRequestOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.evp.model.impl.EVPRequestOrganizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.evp.model.impl.EVPRequestOrganizationImpl}.
 * </p>
 *
 * @author Val Nagy
 * @see EVPRequestOrganization
 * @see com.liferay.evp.model.impl.EVPRequestOrganizationImpl
 * @see com.liferay.evp.model.impl.EVPRequestOrganizationModelImpl
 * @generated
 */
public interface EVPRequestOrganizationModel extends AuditedModel,
	BaseModel<EVPRequestOrganization> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e v p request organization model instance should use the {@link EVPRequestOrganization} interface instead.
	 */

	/**
	 * Returns the primary key of this e v p request organization.
	 *
	 * @return the primary key of this e v p request organization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e v p request organization.
	 *
	 * @param primaryKey the primary key of this e v p request organization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evp request organization ID of this e v p request organization.
	 *
	 * @return the evp request organization ID of this e v p request organization
	 */
	public long getEvpRequestOrganizationId();

	/**
	 * Sets the evp request organization ID of this e v p request organization.
	 *
	 * @param evpRequestOrganizationId the evp request organization ID of this e v p request organization
	 */
	public void setEvpRequestOrganizationId(long evpRequestOrganizationId);

	/**
	 * Returns the company ID of this e v p request organization.
	 *
	 * @return the company ID of this e v p request organization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e v p request organization.
	 *
	 * @param companyId the company ID of this e v p request organization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e v p request organization.
	 *
	 * @return the user ID of this e v p request organization
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e v p request organization.
	 *
	 * @param userId the user ID of this e v p request organization
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e v p request organization.
	 *
	 * @return the user uuid of this e v p request organization
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e v p request organization.
	 *
	 * @param userUuid the user uuid of this e v p request organization
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e v p request organization.
	 *
	 * @return the user name of this e v p request organization
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e v p request organization.
	 *
	 * @param userName the user name of this e v p request organization
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e v p request organization.
	 *
	 * @return the create date of this e v p request organization
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e v p request organization.
	 *
	 * @param createDate the create date of this e v p request organization
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e v p request organization.
	 *
	 * @return the modified date of this e v p request organization
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e v p request organization.
	 *
	 * @param modifiedDate the modified date of this e v p request organization
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this e v p request organization.
	 *
	 * @return the organization ID of this e v p request organization
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this e v p request organization.
	 *
	 * @param organizationId the organization ID of this e v p request organization
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the subsidiary group ID of this e v p request organization.
	 *
	 * @return the subsidiary group ID of this e v p request organization
	 */
	public long getSubsidiaryGroupId();

	/**
	 * Sets the subsidiary group ID of this e v p request organization.
	 *
	 * @param subsidiaryGroupId the subsidiary group ID of this e v p request organization
	 */
	public void setSubsidiaryGroupId(long subsidiaryGroupId);

	/**
	 * Returns the description of this e v p request organization.
	 *
	 * @return the description of this e v p request organization
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this e v p request organization.
	 *
	 * @param description the description of this e v p request organization
	 */
	public void setDescription(String description);

	/**
	 * Returns the tax identification number of this e v p request organization.
	 *
	 * @return the tax identification number of this e v p request organization
	 */
	@AutoEscape
	public String getTaxIdentificationNumber();

	/**
	 * Sets the tax identification number of this e v p request organization.
	 *
	 * @param taxIdentificationNumber the tax identification number of this e v p request organization
	 */
	public void setTaxIdentificationNumber(String taxIdentificationNumber);

	/**
	 * Returns the nonprofit type of this e v p request organization.
	 *
	 * @return the nonprofit type of this e v p request organization
	 */
	public int getNonprofitType();

	/**
	 * Sets the nonprofit type of this e v p request organization.
	 *
	 * @param nonprofitType the nonprofit type of this e v p request organization
	 */
	public void setNonprofitType(int nonprofitType);

	/**
	 * Returns the verified of this e v p request organization.
	 *
	 * @return the verified of this e v p request organization
	 */
	public boolean getVerified();

	/**
	 * Returns <code>true</code> if this e v p request organization is verified.
	 *
	 * @return <code>true</code> if this e v p request organization is verified; <code>false</code> otherwise
	 */
	public boolean isVerified();

	/**
	 * Sets whether this e v p request organization is verified.
	 *
	 * @param verified the verified of this e v p request organization
	 */
	public void setVerified(boolean verified);

	/**
	 * Returns the shared of this e v p request organization.
	 *
	 * @return the shared of this e v p request organization
	 */
	public boolean getShared();

	/**
	 * Returns <code>true</code> if this e v p request organization is shared.
	 *
	 * @return <code>true</code> if this e v p request organization is shared; <code>false</code> otherwise
	 */
	public boolean isShared();

	/**
	 * Sets whether this e v p request organization is shared.
	 *
	 * @param shared the shared of this e v p request organization
	 */
	public void setShared(boolean shared);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.evp.model.EVPRequestOrganization evpRequestOrganization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.evp.model.EVPRequestOrganization> toCacheModel();

	@Override
	public com.liferay.evp.model.EVPRequestOrganization toEscapedModel();

	@Override
	public com.liferay.evp.model.EVPRequestOrganization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}