create table EVPDivision (
	evpDivisionId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	organizationId LONG,
	parentEVPDivisionId LONG,
	abbreviation VARCHAR(75) null,
	type_ INTEGER
);

create table EVPEmployee (
	evpEmployeeId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	employeeUserId LONG,
	managerUserId LONG,
	subsidiaryEVPDivisionId LONG,
	employmentType INTEGER,
	hireDate DATE null
);

create table EVPGrantRequest (
	evpGrantRequestId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	contactEmailAddressId LONG,
	contactPhoneId LONG,
	contactUserId LONG,
	evpRequestOrganizationId LONG,
	parentEVPGrantRequestId LONG,
	requestOrganizationAddressId LONG,
	requestOrganizationWebsiteId LONG,
	subsidiaryGroupId LONG,
	description VARCHAR(75) null,
	employmentType INTEGER,
	employmentHoursPerWeek INTEGER,
	purpose VARCHAR(75) null,
	purposeOther VARCHAR(75) null,
	behalfOf VARCHAR(75) null,
	behalfOfOther VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table EVPGrantTransaction (
	evpGrantTransactionId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	evpGrantRequestId LONG,
	fileEntryId LONG,
	grantType INTEGER,
	amount DOUBLE,
	currencyCode VARCHAR(75) null,
	date_ DATE null,
	note VARCHAR(75) null,
	number_ VARCHAR(75) null,
	bankBICCode VARCHAR(75) null,
	bankIBANCode VARCHAR(75) null,
	bankName VARCHAR(75) null,
	purposeOfUse VARCHAR(75) null
);

create table EVPKaleoForkInstance (
	evpKaleoForkInstanceId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	classNameId LONG,
	classPK LONG,
	type_ INTEGER,
	status INTEGER
);

create table EVPRequestOrganization (
	evpRequestOrganizationId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	organizationId LONG,
	subsidiaryGroupId LONG,
	description VARCHAR(75) null,
	taxIdentificationNumber VARCHAR(75) null,
	nonprofitType INTEGER,
	verified BOOLEAN,
	shared BOOLEAN
);

create table EVPServiceRequest (
	evpServiceRequestId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	contactEmailAddressId LONG,
	contactPhoneId LONG,
	contactUserId LONG,
	evpRequestOrganizationId LONG,
	managerUserId LONG,
	parentEVPServiceRequestId LONG,
	requestOrganizationAddressId LONG,
	requestOrganizationWebsiteId LONG,
	subsidiaryGroupId LONG,
	description VARCHAR(75) null,
	employmentType INTEGER,
	employmentHoursPerWeek INTEGER,
	purpose VARCHAR(75) null,
	purposeOther VARCHAR(75) null,
	behalfOf VARCHAR(75) null,
	behalfOfOther VARCHAR(75) null,
	requestedStartDate DATE null,
	requestedEndDate DATE null,
	requestedTotalHours INTEGER,
	promoteTrip BOOLEAN,
	confirmedStartDate DATE null,
	confirmedEndDate DATE null,
	confirmedTotalHours INTEGER,
	contactBenefit VARCHAR(75) null,
	contactComments VARCHAR(75) null,
	hash VARCHAR(75) null,
	feedbackDescription VARCHAR(75) null,
	employeeBenefit VARCHAR(75) null,
	recipientBenefit VARCHAR(75) null,
	shareStory BOOLEAN,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);