/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model.impl;

import com.liferay.evp.model.EVPGrantRequest;
import com.liferay.evp.model.EVPGrantRequestModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EVPGrantRequest service. Represents a row in the &quot;EVPGrantRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EVPGrantRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EVPGrantRequestImpl}.
 * </p>
 *
 * @author Val Nagy
 * @see EVPGrantRequestImpl
 * @generated
 */
public class EVPGrantRequestModelImpl
	extends BaseModelImpl<EVPGrantRequest> implements EVPGrantRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a evp grant request model instance should use the <code>EVPGrantRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "EVPGrantRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"evpGrantRequestId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"contactEmailAddressId", Types.BIGINT},
		{"contactPhoneId", Types.BIGINT}, {"contactUserId", Types.BIGINT},
		{"evpRequestOrganizationId", Types.BIGINT},
		{"parentEVPGrantRequestId", Types.BIGINT},
		{"requestOrganizationAddressId", Types.BIGINT},
		{"requestOrganizationWebsiteId", Types.BIGINT},
		{"subsidiaryGroupId", Types.BIGINT}, {"description", Types.VARCHAR},
		{"employmentType", Types.INTEGER},
		{"employmentHoursPerWeek", Types.INTEGER}, {"purpose", Types.VARCHAR},
		{"purposeOther", Types.VARCHAR}, {"behalfOf", Types.VARCHAR},
		{"behalfOfOther", Types.VARCHAR}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("evpGrantRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("contactEmailAddressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contactPhoneId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contactUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("evpRequestOrganizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentEVPGrantRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("requestOrganizationAddressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("requestOrganizationWebsiteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subsidiaryGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employmentType", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("employmentHoursPerWeek", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("purpose", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("purposeOther", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("behalfOf", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("behalfOfOther", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EVPGrantRequest (evpGrantRequestId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,contactEmailAddressId LONG,contactPhoneId LONG,contactUserId LONG,evpRequestOrganizationId LONG,parentEVPGrantRequestId LONG,requestOrganizationAddressId LONG,requestOrganizationWebsiteId LONG,subsidiaryGroupId LONG,description VARCHAR(75) null,employmentType INTEGER,employmentHoursPerWeek INTEGER,purpose VARCHAR(75) null,purposeOther VARCHAR(75) null,behalfOf VARCHAR(75) null,behalfOfOther VARCHAR(75) null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EVPGrantRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY evpGrantRequest.evpGrantRequestId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EVPGrantRequest.evpGrantRequestId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EVPGRANTREQUESTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EVPGrantRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _evpGrantRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEvpGrantRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _evpGrantRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EVPGrantRequest.class;
	}

	@Override
	public String getModelClassName() {
		return EVPGrantRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EVPGrantRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EVPGrantRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EVPGrantRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EVPGrantRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EVPGrantRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EVPGrantRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EVPGrantRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EVPGrantRequest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EVPGrantRequest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EVPGrantRequest>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EVPGrantRequest.class.getClassLoader(), EVPGrantRequest.class,
			ModelWrapper.class);

		try {
			Constructor<EVPGrantRequest> constructor =
				(Constructor<EVPGrantRequest>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EVPGrantRequest, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EVPGrantRequest, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EVPGrantRequest, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<EVPGrantRequest, Object>>();
		Map<String, BiConsumer<EVPGrantRequest, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EVPGrantRequest, ?>>();

		attributeGetterFunctions.put(
			"evpGrantRequestId", EVPGrantRequest::getEvpGrantRequestId);
		attributeSetterBiConsumers.put(
			"evpGrantRequestId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setEvpGrantRequestId);
		attributeGetterFunctions.put(
			"companyId", EVPGrantRequest::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EVPGrantRequest, Long>)EVPGrantRequest::setCompanyId);
		attributeGetterFunctions.put("userId", EVPGrantRequest::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EVPGrantRequest, Long>)EVPGrantRequest::setUserId);
		attributeGetterFunctions.put("userName", EVPGrantRequest::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EVPGrantRequest, String>)EVPGrantRequest::setUserName);
		attributeGetterFunctions.put(
			"createDate", EVPGrantRequest::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EVPGrantRequest, Date>)EVPGrantRequest::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EVPGrantRequest::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EVPGrantRequest, Date>)
				EVPGrantRequest::setModifiedDate);
		attributeGetterFunctions.put(
			"contactEmailAddressId", EVPGrantRequest::getContactEmailAddressId);
		attributeSetterBiConsumers.put(
			"contactEmailAddressId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setContactEmailAddressId);
		attributeGetterFunctions.put(
			"contactPhoneId", EVPGrantRequest::getContactPhoneId);
		attributeSetterBiConsumers.put(
			"contactPhoneId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setContactPhoneId);
		attributeGetterFunctions.put(
			"contactUserId", EVPGrantRequest::getContactUserId);
		attributeSetterBiConsumers.put(
			"contactUserId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setContactUserId);
		attributeGetterFunctions.put(
			"evpRequestOrganizationId",
			EVPGrantRequest::getEvpRequestOrganizationId);
		attributeSetterBiConsumers.put(
			"evpRequestOrganizationId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setEvpRequestOrganizationId);
		attributeGetterFunctions.put(
			"parentEVPGrantRequestId",
			EVPGrantRequest::getParentEVPGrantRequestId);
		attributeSetterBiConsumers.put(
			"parentEVPGrantRequestId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setParentEVPGrantRequestId);
		attributeGetterFunctions.put(
			"requestOrganizationAddressId",
			EVPGrantRequest::getRequestOrganizationAddressId);
		attributeSetterBiConsumers.put(
			"requestOrganizationAddressId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setRequestOrganizationAddressId);
		attributeGetterFunctions.put(
			"requestOrganizationWebsiteId",
			EVPGrantRequest::getRequestOrganizationWebsiteId);
		attributeSetterBiConsumers.put(
			"requestOrganizationWebsiteId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setRequestOrganizationWebsiteId);
		attributeGetterFunctions.put(
			"subsidiaryGroupId", EVPGrantRequest::getSubsidiaryGroupId);
		attributeSetterBiConsumers.put(
			"subsidiaryGroupId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setSubsidiaryGroupId);
		attributeGetterFunctions.put(
			"description", EVPGrantRequest::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<EVPGrantRequest, String>)
				EVPGrantRequest::setDescription);
		attributeGetterFunctions.put(
			"employmentType", EVPGrantRequest::getEmploymentType);
		attributeSetterBiConsumers.put(
			"employmentType",
			(BiConsumer<EVPGrantRequest, Integer>)
				EVPGrantRequest::setEmploymentType);
		attributeGetterFunctions.put(
			"employmentHoursPerWeek",
			EVPGrantRequest::getEmploymentHoursPerWeek);
		attributeSetterBiConsumers.put(
			"employmentHoursPerWeek",
			(BiConsumer<EVPGrantRequest, Integer>)
				EVPGrantRequest::setEmploymentHoursPerWeek);
		attributeGetterFunctions.put("purpose", EVPGrantRequest::getPurpose);
		attributeSetterBiConsumers.put(
			"purpose",
			(BiConsumer<EVPGrantRequest, String>)EVPGrantRequest::setPurpose);
		attributeGetterFunctions.put(
			"purposeOther", EVPGrantRequest::getPurposeOther);
		attributeSetterBiConsumers.put(
			"purposeOther",
			(BiConsumer<EVPGrantRequest, String>)
				EVPGrantRequest::setPurposeOther);
		attributeGetterFunctions.put("behalfOf", EVPGrantRequest::getBehalfOf);
		attributeSetterBiConsumers.put(
			"behalfOf",
			(BiConsumer<EVPGrantRequest, String>)EVPGrantRequest::setBehalfOf);
		attributeGetterFunctions.put(
			"behalfOfOther", EVPGrantRequest::getBehalfOfOther);
		attributeSetterBiConsumers.put(
			"behalfOfOther",
			(BiConsumer<EVPGrantRequest, String>)
				EVPGrantRequest::setBehalfOfOther);
		attributeGetterFunctions.put("status", EVPGrantRequest::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<EVPGrantRequest, Integer>)EVPGrantRequest::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", EVPGrantRequest::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<EVPGrantRequest, Long>)
				EVPGrantRequest::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", EVPGrantRequest::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<EVPGrantRequest, String>)
				EVPGrantRequest::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", EVPGrantRequest::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<EVPGrantRequest, Date>)EVPGrantRequest::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getEvpGrantRequestId() {
		return _evpGrantRequestId;
	}

	@Override
	public void setEvpGrantRequestId(long evpGrantRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_evpGrantRequestId = evpGrantRequestId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getContactEmailAddressId() {
		return _contactEmailAddressId;
	}

	@Override
	public void setContactEmailAddressId(long contactEmailAddressId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactEmailAddressId = contactEmailAddressId;
	}

	@Override
	public long getContactPhoneId() {
		return _contactPhoneId;
	}

	@Override
	public void setContactPhoneId(long contactPhoneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactPhoneId = contactPhoneId;
	}

	@Override
	public long getContactUserId() {
		return _contactUserId;
	}

	@Override
	public void setContactUserId(long contactUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactUserId = contactUserId;
	}

	@Override
	public String getContactUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getContactUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setContactUserUuid(String contactUserUuid) {
	}

	@Override
	public long getEvpRequestOrganizationId() {
		return _evpRequestOrganizationId;
	}

	@Override
	public void setEvpRequestOrganizationId(long evpRequestOrganizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_evpRequestOrganizationId = evpRequestOrganizationId;
	}

	@Override
	public long getParentEVPGrantRequestId() {
		return _parentEVPGrantRequestId;
	}

	@Override
	public void setParentEVPGrantRequestId(long parentEVPGrantRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentEVPGrantRequestId = parentEVPGrantRequestId;
	}

	@Override
	public long getRequestOrganizationAddressId() {
		return _requestOrganizationAddressId;
	}

	@Override
	public void setRequestOrganizationAddressId(
		long requestOrganizationAddressId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestOrganizationAddressId = requestOrganizationAddressId;
	}

	@Override
	public long getRequestOrganizationWebsiteId() {
		return _requestOrganizationWebsiteId;
	}

	@Override
	public void setRequestOrganizationWebsiteId(
		long requestOrganizationWebsiteId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestOrganizationWebsiteId = requestOrganizationWebsiteId;
	}

	@Override
	public long getSubsidiaryGroupId() {
		return _subsidiaryGroupId;
	}

	@Override
	public void setSubsidiaryGroupId(long subsidiaryGroupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subsidiaryGroupId = subsidiaryGroupId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public int getEmploymentType() {
		return _employmentType;
	}

	@Override
	public void setEmploymentType(int employmentType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employmentType = employmentType;
	}

	@Override
	public int getEmploymentHoursPerWeek() {
		return _employmentHoursPerWeek;
	}

	@Override
	public void setEmploymentHoursPerWeek(int employmentHoursPerWeek) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employmentHoursPerWeek = employmentHoursPerWeek;
	}

	@Override
	public String getPurpose() {
		if (_purpose == null) {
			return "";
		}
		else {
			return _purpose;
		}
	}

	@Override
	public void setPurpose(String purpose) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purpose = purpose;
	}

	@Override
	public String getPurposeOther() {
		if (_purposeOther == null) {
			return "";
		}
		else {
			return _purposeOther;
		}
	}

	@Override
	public void setPurposeOther(String purposeOther) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purposeOther = purposeOther;
	}

	@Override
	public String getBehalfOf() {
		if (_behalfOf == null) {
			return "";
		}
		else {
			return _behalfOf;
		}
	}

	@Override
	public void setBehalfOf(String behalfOf) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_behalfOf = behalfOf;
	}

	@Override
	public String getBehalfOfOther() {
		if (_behalfOfOther == null) {
			return "";
		}
		else {
			return _behalfOfOther;
		}
	}

	@Override
	public void setBehalfOfOther(String behalfOfOther) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_behalfOfOther = behalfOfOther;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EVPGrantRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EVPGrantRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EVPGrantRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EVPGrantRequestImpl evpGrantRequestImpl = new EVPGrantRequestImpl();

		evpGrantRequestImpl.setEvpGrantRequestId(getEvpGrantRequestId());
		evpGrantRequestImpl.setCompanyId(getCompanyId());
		evpGrantRequestImpl.setUserId(getUserId());
		evpGrantRequestImpl.setUserName(getUserName());
		evpGrantRequestImpl.setCreateDate(getCreateDate());
		evpGrantRequestImpl.setModifiedDate(getModifiedDate());
		evpGrantRequestImpl.setContactEmailAddressId(
			getContactEmailAddressId());
		evpGrantRequestImpl.setContactPhoneId(getContactPhoneId());
		evpGrantRequestImpl.setContactUserId(getContactUserId());
		evpGrantRequestImpl.setEvpRequestOrganizationId(
			getEvpRequestOrganizationId());
		evpGrantRequestImpl.setParentEVPGrantRequestId(
			getParentEVPGrantRequestId());
		evpGrantRequestImpl.setRequestOrganizationAddressId(
			getRequestOrganizationAddressId());
		evpGrantRequestImpl.setRequestOrganizationWebsiteId(
			getRequestOrganizationWebsiteId());
		evpGrantRequestImpl.setSubsidiaryGroupId(getSubsidiaryGroupId());
		evpGrantRequestImpl.setDescription(getDescription());
		evpGrantRequestImpl.setEmploymentType(getEmploymentType());
		evpGrantRequestImpl.setEmploymentHoursPerWeek(
			getEmploymentHoursPerWeek());
		evpGrantRequestImpl.setPurpose(getPurpose());
		evpGrantRequestImpl.setPurposeOther(getPurposeOther());
		evpGrantRequestImpl.setBehalfOf(getBehalfOf());
		evpGrantRequestImpl.setBehalfOfOther(getBehalfOfOther());
		evpGrantRequestImpl.setStatus(getStatus());
		evpGrantRequestImpl.setStatusByUserId(getStatusByUserId());
		evpGrantRequestImpl.setStatusByUserName(getStatusByUserName());
		evpGrantRequestImpl.setStatusDate(getStatusDate());

		evpGrantRequestImpl.resetOriginalValues();

		return evpGrantRequestImpl;
	}

	@Override
	public int compareTo(EVPGrantRequest evpGrantRequest) {
		long primaryKey = evpGrantRequest.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EVPGrantRequest)) {
			return false;
		}

		EVPGrantRequest evpGrantRequest = (EVPGrantRequest)object;

		long primaryKey = evpGrantRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EVPGrantRequest> toCacheModel() {
		EVPGrantRequestCacheModel evpGrantRequestCacheModel =
			new EVPGrantRequestCacheModel();

		evpGrantRequestCacheModel.evpGrantRequestId = getEvpGrantRequestId();

		evpGrantRequestCacheModel.companyId = getCompanyId();

		evpGrantRequestCacheModel.userId = getUserId();

		evpGrantRequestCacheModel.userName = getUserName();

		String userName = evpGrantRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			evpGrantRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			evpGrantRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			evpGrantRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			evpGrantRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			evpGrantRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		evpGrantRequestCacheModel.contactEmailAddressId =
			getContactEmailAddressId();

		evpGrantRequestCacheModel.contactPhoneId = getContactPhoneId();

		evpGrantRequestCacheModel.contactUserId = getContactUserId();

		evpGrantRequestCacheModel.evpRequestOrganizationId =
			getEvpRequestOrganizationId();

		evpGrantRequestCacheModel.parentEVPGrantRequestId =
			getParentEVPGrantRequestId();

		evpGrantRequestCacheModel.requestOrganizationAddressId =
			getRequestOrganizationAddressId();

		evpGrantRequestCacheModel.requestOrganizationWebsiteId =
			getRequestOrganizationWebsiteId();

		evpGrantRequestCacheModel.subsidiaryGroupId = getSubsidiaryGroupId();

		evpGrantRequestCacheModel.description = getDescription();

		String description = evpGrantRequestCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			evpGrantRequestCacheModel.description = null;
		}

		evpGrantRequestCacheModel.employmentType = getEmploymentType();

		evpGrantRequestCacheModel.employmentHoursPerWeek =
			getEmploymentHoursPerWeek();

		evpGrantRequestCacheModel.purpose = getPurpose();

		String purpose = evpGrantRequestCacheModel.purpose;

		if ((purpose != null) && (purpose.length() == 0)) {
			evpGrantRequestCacheModel.purpose = null;
		}

		evpGrantRequestCacheModel.purposeOther = getPurposeOther();

		String purposeOther = evpGrantRequestCacheModel.purposeOther;

		if ((purposeOther != null) && (purposeOther.length() == 0)) {
			evpGrantRequestCacheModel.purposeOther = null;
		}

		evpGrantRequestCacheModel.behalfOf = getBehalfOf();

		String behalfOf = evpGrantRequestCacheModel.behalfOf;

		if ((behalfOf != null) && (behalfOf.length() == 0)) {
			evpGrantRequestCacheModel.behalfOf = null;
		}

		evpGrantRequestCacheModel.behalfOfOther = getBehalfOfOther();

		String behalfOfOther = evpGrantRequestCacheModel.behalfOfOther;

		if ((behalfOfOther != null) && (behalfOfOther.length() == 0)) {
			evpGrantRequestCacheModel.behalfOfOther = null;
		}

		evpGrantRequestCacheModel.status = getStatus();

		evpGrantRequestCacheModel.statusByUserId = getStatusByUserId();

		evpGrantRequestCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = evpGrantRequestCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			evpGrantRequestCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			evpGrantRequestCacheModel.statusDate = statusDate.getTime();
		}
		else {
			evpGrantRequestCacheModel.statusDate = Long.MIN_VALUE;
		}

		return evpGrantRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EVPGrantRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EVPGrantRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EVPGrantRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EVPGrantRequest)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EVPGrantRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EVPGrantRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EVPGrantRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EVPGrantRequest)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EVPGrantRequest>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _evpGrantRequestId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _contactEmailAddressId;
	private long _contactPhoneId;
	private long _contactUserId;
	private long _evpRequestOrganizationId;
	private long _parentEVPGrantRequestId;
	private long _requestOrganizationAddressId;
	private long _requestOrganizationWebsiteId;
	private long _subsidiaryGroupId;
	private String _description;
	private int _employmentType;
	private int _employmentHoursPerWeek;
	private String _purpose;
	private String _purposeOther;
	private String _behalfOf;
	private String _behalfOfOther;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		Function<EVPGrantRequest, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EVPGrantRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("evpGrantRequestId", _evpGrantRequestId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"contactEmailAddressId", _contactEmailAddressId);
		_columnOriginalValues.put("contactPhoneId", _contactPhoneId);
		_columnOriginalValues.put("contactUserId", _contactUserId);
		_columnOriginalValues.put(
			"evpRequestOrganizationId", _evpRequestOrganizationId);
		_columnOriginalValues.put(
			"parentEVPGrantRequestId", _parentEVPGrantRequestId);
		_columnOriginalValues.put(
			"requestOrganizationAddressId", _requestOrganizationAddressId);
		_columnOriginalValues.put(
			"requestOrganizationWebsiteId", _requestOrganizationWebsiteId);
		_columnOriginalValues.put("subsidiaryGroupId", _subsidiaryGroupId);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("employmentType", _employmentType);
		_columnOriginalValues.put(
			"employmentHoursPerWeek", _employmentHoursPerWeek);
		_columnOriginalValues.put("purpose", _purpose);
		_columnOriginalValues.put("purposeOther", _purposeOther);
		_columnOriginalValues.put("behalfOf", _behalfOf);
		_columnOriginalValues.put("behalfOfOther", _behalfOfOther);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("evpGrantRequestId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("userName", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("contactEmailAddressId", 64L);

		columnBitmasks.put("contactPhoneId", 128L);

		columnBitmasks.put("contactUserId", 256L);

		columnBitmasks.put("evpRequestOrganizationId", 512L);

		columnBitmasks.put("parentEVPGrantRequestId", 1024L);

		columnBitmasks.put("requestOrganizationAddressId", 2048L);

		columnBitmasks.put("requestOrganizationWebsiteId", 4096L);

		columnBitmasks.put("subsidiaryGroupId", 8192L);

		columnBitmasks.put("description", 16384L);

		columnBitmasks.put("employmentType", 32768L);

		columnBitmasks.put("employmentHoursPerWeek", 65536L);

		columnBitmasks.put("purpose", 131072L);

		columnBitmasks.put("purposeOther", 262144L);

		columnBitmasks.put("behalfOf", 524288L);

		columnBitmasks.put("behalfOfOther", 1048576L);

		columnBitmasks.put("status", 2097152L);

		columnBitmasks.put("statusByUserId", 4194304L);

		columnBitmasks.put("statusByUserName", 8388608L);

		columnBitmasks.put("statusDate", 16777216L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EVPGrantRequest _escapedModel;

}