/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model.impl;

import com.liferay.evp.model.EVPKaleoForkInstance;
import com.liferay.evp.model.EVPKaleoForkInstanceModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EVPKaleoForkInstance service. Represents a row in the &quot;EVPKaleoForkInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EVPKaleoForkInstanceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EVPKaleoForkInstanceImpl}.
 * </p>
 *
 * @author Val Nagy
 * @see EVPKaleoForkInstanceImpl
 * @generated
 */
public class EVPKaleoForkInstanceModelImpl
	extends BaseModelImpl<EVPKaleoForkInstance>
	implements EVPKaleoForkInstanceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a evp kaleo fork instance model instance should use the <code>EVPKaleoForkInstance</code> interface instead.
	 */
	public static final String TABLE_NAME = "EVPKaleoForkInstance";

	public static final Object[][] TABLE_COLUMNS = {
		{"evpKaleoForkInstanceId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"type_", Types.INTEGER}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("evpKaleoForkInstanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EVPKaleoForkInstance (evpKaleoForkInstanceId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,type_ INTEGER,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table EVPKaleoForkInstance";

	public static final String ORDER_BY_JPQL =
		" ORDER BY evpKaleoForkInstance.evpKaleoForkInstanceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EVPKaleoForkInstance.evpKaleoForkInstanceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EVPKALEOFORKINSTANCEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EVPKaleoForkInstanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _evpKaleoForkInstanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEvpKaleoForkInstanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _evpKaleoForkInstanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EVPKaleoForkInstance.class;
	}

	@Override
	public String getModelClassName() {
		return EVPKaleoForkInstance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EVPKaleoForkInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EVPKaleoForkInstance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EVPKaleoForkInstance, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EVPKaleoForkInstance)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EVPKaleoForkInstance, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EVPKaleoForkInstance, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EVPKaleoForkInstance)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EVPKaleoForkInstance, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EVPKaleoForkInstance, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EVPKaleoForkInstance>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EVPKaleoForkInstance.class.getClassLoader(),
			EVPKaleoForkInstance.class, ModelWrapper.class);

		try {
			Constructor<EVPKaleoForkInstance> constructor =
				(Constructor<EVPKaleoForkInstance>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EVPKaleoForkInstance, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EVPKaleoForkInstance, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EVPKaleoForkInstance, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EVPKaleoForkInstance, Object>>();
		Map<String, BiConsumer<EVPKaleoForkInstance, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EVPKaleoForkInstance, ?>>();

		attributeGetterFunctions.put(
			"evpKaleoForkInstanceId",
			EVPKaleoForkInstance::getEvpKaleoForkInstanceId);
		attributeSetterBiConsumers.put(
			"evpKaleoForkInstanceId",
			(BiConsumer<EVPKaleoForkInstance, Long>)
				EVPKaleoForkInstance::setEvpKaleoForkInstanceId);
		attributeGetterFunctions.put(
			"companyId", EVPKaleoForkInstance::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EVPKaleoForkInstance, Long>)
				EVPKaleoForkInstance::setCompanyId);
		attributeGetterFunctions.put("userId", EVPKaleoForkInstance::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EVPKaleoForkInstance, Long>)
				EVPKaleoForkInstance::setUserId);
		attributeGetterFunctions.put(
			"userName", EVPKaleoForkInstance::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EVPKaleoForkInstance, String>)
				EVPKaleoForkInstance::setUserName);
		attributeGetterFunctions.put(
			"createDate", EVPKaleoForkInstance::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EVPKaleoForkInstance, Date>)
				EVPKaleoForkInstance::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EVPKaleoForkInstance::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EVPKaleoForkInstance, Date>)
				EVPKaleoForkInstance::setModifiedDate);
		attributeGetterFunctions.put(
			"classNameId", EVPKaleoForkInstance::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<EVPKaleoForkInstance, Long>)
				EVPKaleoForkInstance::setClassNameId);
		attributeGetterFunctions.put(
			"classPK", EVPKaleoForkInstance::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<EVPKaleoForkInstance, Long>)
				EVPKaleoForkInstance::setClassPK);
		attributeGetterFunctions.put("type", EVPKaleoForkInstance::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<EVPKaleoForkInstance, Integer>)
				EVPKaleoForkInstance::setType);
		attributeGetterFunctions.put("status", EVPKaleoForkInstance::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<EVPKaleoForkInstance, Integer>)
				EVPKaleoForkInstance::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getEvpKaleoForkInstanceId() {
		return _evpKaleoForkInstanceId;
	}

	@Override
	public void setEvpKaleoForkInstanceId(long evpKaleoForkInstanceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_evpKaleoForkInstanceId = evpKaleoForkInstanceId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EVPKaleoForkInstance.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EVPKaleoForkInstance toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EVPKaleoForkInstance>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EVPKaleoForkInstanceImpl evpKaleoForkInstanceImpl =
			new EVPKaleoForkInstanceImpl();

		evpKaleoForkInstanceImpl.setEvpKaleoForkInstanceId(
			getEvpKaleoForkInstanceId());
		evpKaleoForkInstanceImpl.setCompanyId(getCompanyId());
		evpKaleoForkInstanceImpl.setUserId(getUserId());
		evpKaleoForkInstanceImpl.setUserName(getUserName());
		evpKaleoForkInstanceImpl.setCreateDate(getCreateDate());
		evpKaleoForkInstanceImpl.setModifiedDate(getModifiedDate());
		evpKaleoForkInstanceImpl.setClassNameId(getClassNameId());
		evpKaleoForkInstanceImpl.setClassPK(getClassPK());
		evpKaleoForkInstanceImpl.setType(getType());
		evpKaleoForkInstanceImpl.setStatus(getStatus());

		evpKaleoForkInstanceImpl.resetOriginalValues();

		return evpKaleoForkInstanceImpl;
	}

	@Override
	public int compareTo(EVPKaleoForkInstance evpKaleoForkInstance) {
		long primaryKey = evpKaleoForkInstance.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EVPKaleoForkInstance)) {
			return false;
		}

		EVPKaleoForkInstance evpKaleoForkInstance =
			(EVPKaleoForkInstance)object;

		long primaryKey = evpKaleoForkInstance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EVPKaleoForkInstance> toCacheModel() {
		EVPKaleoForkInstanceCacheModel evpKaleoForkInstanceCacheModel =
			new EVPKaleoForkInstanceCacheModel();

		evpKaleoForkInstanceCacheModel.evpKaleoForkInstanceId =
			getEvpKaleoForkInstanceId();

		evpKaleoForkInstanceCacheModel.companyId = getCompanyId();

		evpKaleoForkInstanceCacheModel.userId = getUserId();

		evpKaleoForkInstanceCacheModel.userName = getUserName();

		String userName = evpKaleoForkInstanceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			evpKaleoForkInstanceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			evpKaleoForkInstanceCacheModel.createDate = createDate.getTime();
		}
		else {
			evpKaleoForkInstanceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			evpKaleoForkInstanceCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			evpKaleoForkInstanceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		evpKaleoForkInstanceCacheModel.classNameId = getClassNameId();

		evpKaleoForkInstanceCacheModel.classPK = getClassPK();

		evpKaleoForkInstanceCacheModel.type = getType();

		evpKaleoForkInstanceCacheModel.status = getStatus();

		return evpKaleoForkInstanceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EVPKaleoForkInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EVPKaleoForkInstance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EVPKaleoForkInstance, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((EVPKaleoForkInstance)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EVPKaleoForkInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EVPKaleoForkInstance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EVPKaleoForkInstance, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((EVPKaleoForkInstance)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EVPKaleoForkInstance>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _evpKaleoForkInstanceId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private int _type;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EVPKaleoForkInstance, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EVPKaleoForkInstance)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"evpKaleoForkInstanceId", _evpKaleoForkInstanceId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("evpKaleoForkInstanceId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("userName", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("classNameId", 64L);

		columnBitmasks.put("classPK", 128L);

		columnBitmasks.put("type_", 256L);

		columnBitmasks.put("status", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EVPKaleoForkInstance _escapedModel;

}