/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EVPDivision service. Represents a row in the &quot;EVPDivision&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.evp.model.impl.EVPDivisionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.evp.model.impl.EVPDivisionImpl}.
 * </p>
 *
 * @author Val Nagy
 * @see EVPDivision
 * @see com.liferay.evp.model.impl.EVPDivisionImpl
 * @see com.liferay.evp.model.impl.EVPDivisionModelImpl
 * @generated
 */
public interface EVPDivisionModel extends AuditedModel, BaseModel<EVPDivision> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e v p division model instance should use the {@link EVPDivision} interface instead.
	 */

	/**
	 * Returns the primary key of this e v p division.
	 *
	 * @return the primary key of this e v p division
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e v p division.
	 *
	 * @param primaryKey the primary key of this e v p division
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evp division ID of this e v p division.
	 *
	 * @return the evp division ID of this e v p division
	 */
	public long getEvpDivisionId();

	/**
	 * Sets the evp division ID of this e v p division.
	 *
	 * @param evpDivisionId the evp division ID of this e v p division
	 */
	public void setEvpDivisionId(long evpDivisionId);

	/**
	 * Returns the company ID of this e v p division.
	 *
	 * @return the company ID of this e v p division
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e v p division.
	 *
	 * @param companyId the company ID of this e v p division
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e v p division.
	 *
	 * @return the user ID of this e v p division
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e v p division.
	 *
	 * @param userId the user ID of this e v p division
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e v p division.
	 *
	 * @return the user uuid of this e v p division
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this e v p division.
	 *
	 * @param userUuid the user uuid of this e v p division
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e v p division.
	 *
	 * @return the user name of this e v p division
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e v p division.
	 *
	 * @param userName the user name of this e v p division
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e v p division.
	 *
	 * @return the create date of this e v p division
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e v p division.
	 *
	 * @param createDate the create date of this e v p division
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e v p division.
	 *
	 * @return the modified date of this e v p division
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e v p division.
	 *
	 * @param modifiedDate the modified date of this e v p division
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this e v p division.
	 *
	 * @return the organization ID of this e v p division
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this e v p division.
	 *
	 * @param organizationId the organization ID of this e v p division
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the parent e v p division ID of this e v p division.
	 *
	 * @return the parent e v p division ID of this e v p division
	 */
	public long getParentEVPDivisionId();

	/**
	 * Sets the parent e v p division ID of this e v p division.
	 *
	 * @param parentEVPDivisionId the parent e v p division ID of this e v p division
	 */
	public void setParentEVPDivisionId(long parentEVPDivisionId);

	/**
	 * Returns the abbreviation of this e v p division.
	 *
	 * @return the abbreviation of this e v p division
	 */
	@AutoEscape
	public String getAbbreviation();

	/**
	 * Sets the abbreviation of this e v p division.
	 *
	 * @param abbreviation the abbreviation of this e v p division
	 */
	public void setAbbreviation(String abbreviation);

	/**
	 * Returns the type of this e v p division.
	 *
	 * @return the type of this e v p division
	 */
	public int getType();

	/**
	 * Sets the type of this e v p division.
	 *
	 * @param type the type of this e v p division
	 */
	public void setType(int type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.evp.model.EVPDivision evpDivision);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.evp.model.EVPDivision> toCacheModel();

	@Override
	public com.liferay.evp.model.EVPDivision toEscapedModel();

	@Override
	public com.liferay.evp.model.EVPDivision toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}