/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EVPDivision service. Represents a row in the &quot;EVPDivision&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.evp.model.impl.EVPDivisionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.evp.model.impl.EVPDivisionImpl</code>.
 * </p>
 *
 * @author Val Nagy
 * @see EVPDivision
 * @generated
 */
@ProviderType
public interface EVPDivisionModel
	extends AuditedModel, BaseModel<EVPDivision>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evp division model instance should use the {@link EVPDivision} interface instead.
	 */

	/**
	 * Returns the primary key of this evp division.
	 *
	 * @return the primary key of this evp division
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this evp division.
	 *
	 * @param primaryKey the primary key of this evp division
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evp division ID of this evp division.
	 *
	 * @return the evp division ID of this evp division
	 */
	public long getEvpDivisionId();

	/**
	 * Sets the evp division ID of this evp division.
	 *
	 * @param evpDivisionId the evp division ID of this evp division
	 */
	public void setEvpDivisionId(long evpDivisionId);

	/**
	 * Returns the company ID of this evp division.
	 *
	 * @return the company ID of this evp division
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this evp division.
	 *
	 * @param companyId the company ID of this evp division
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this evp division.
	 *
	 * @return the user ID of this evp division
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this evp division.
	 *
	 * @param userId the user ID of this evp division
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this evp division.
	 *
	 * @return the user uuid of this evp division
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this evp division.
	 *
	 * @param userUuid the user uuid of this evp division
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this evp division.
	 *
	 * @return the user name of this evp division
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this evp division.
	 *
	 * @param userName the user name of this evp division
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this evp division.
	 *
	 * @return the create date of this evp division
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this evp division.
	 *
	 * @param createDate the create date of this evp division
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this evp division.
	 *
	 * @return the modified date of this evp division
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this evp division.
	 *
	 * @param modifiedDate the modified date of this evp division
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this evp division.
	 *
	 * @return the organization ID of this evp division
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this evp division.
	 *
	 * @param organizationId the organization ID of this evp division
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the parent evp division ID of this evp division.
	 *
	 * @return the parent evp division ID of this evp division
	 */
	public long getParentEVPDivisionId();

	/**
	 * Sets the parent evp division ID of this evp division.
	 *
	 * @param parentEVPDivisionId the parent evp division ID of this evp division
	 */
	public void setParentEVPDivisionId(long parentEVPDivisionId);

	/**
	 * Returns the abbreviation of this evp division.
	 *
	 * @return the abbreviation of this evp division
	 */
	@AutoEscape
	public String getAbbreviation();

	/**
	 * Sets the abbreviation of this evp division.
	 *
	 * @param abbreviation the abbreviation of this evp division
	 */
	public void setAbbreviation(String abbreviation);

	/**
	 * Returns the type of this evp division.
	 *
	 * @return the type of this evp division
	 */
	public int getType();

	/**
	 * Sets the type of this evp division.
	 *
	 * @param type the type of this evp division
	 */
	public void setType(int type);

}