/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EVPEmployee service. Represents a row in the &quot;EVPEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.evp.model.impl.EVPEmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.evp.model.impl.EVPEmployeeImpl</code>.
 * </p>
 *
 * @author Val Nagy
 * @see EVPEmployee
 * @generated
 */
@ProviderType
public interface EVPEmployeeModel
	extends AuditedModel, BaseModel<EVPEmployee>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evp employee model instance should use the {@link EVPEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this evp employee.
	 *
	 * @return the primary key of this evp employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this evp employee.
	 *
	 * @param primaryKey the primary key of this evp employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evp employee ID of this evp employee.
	 *
	 * @return the evp employee ID of this evp employee
	 */
	public long getEvpEmployeeId();

	/**
	 * Sets the evp employee ID of this evp employee.
	 *
	 * @param evpEmployeeId the evp employee ID of this evp employee
	 */
	public void setEvpEmployeeId(long evpEmployeeId);

	/**
	 * Returns the company ID of this evp employee.
	 *
	 * @return the company ID of this evp employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this evp employee.
	 *
	 * @param companyId the company ID of this evp employee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this evp employee.
	 *
	 * @return the user ID of this evp employee
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this evp employee.
	 *
	 * @param userId the user ID of this evp employee
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this evp employee.
	 *
	 * @return the user uuid of this evp employee
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this evp employee.
	 *
	 * @param userUuid the user uuid of this evp employee
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this evp employee.
	 *
	 * @return the user name of this evp employee
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this evp employee.
	 *
	 * @param userName the user name of this evp employee
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this evp employee.
	 *
	 * @return the create date of this evp employee
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this evp employee.
	 *
	 * @param createDate the create date of this evp employee
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this evp employee.
	 *
	 * @return the modified date of this evp employee
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this evp employee.
	 *
	 * @param modifiedDate the modified date of this evp employee
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee user ID of this evp employee.
	 *
	 * @return the employee user ID of this evp employee
	 */
	public long getEmployeeUserId();

	/**
	 * Sets the employee user ID of this evp employee.
	 *
	 * @param employeeUserId the employee user ID of this evp employee
	 */
	public void setEmployeeUserId(long employeeUserId);

	/**
	 * Returns the employee user uuid of this evp employee.
	 *
	 * @return the employee user uuid of this evp employee
	 */
	public String getEmployeeUserUuid();

	/**
	 * Sets the employee user uuid of this evp employee.
	 *
	 * @param employeeUserUuid the employee user uuid of this evp employee
	 */
	public void setEmployeeUserUuid(String employeeUserUuid);

	/**
	 * Returns the manager user ID of this evp employee.
	 *
	 * @return the manager user ID of this evp employee
	 */
	public long getManagerUserId();

	/**
	 * Sets the manager user ID of this evp employee.
	 *
	 * @param managerUserId the manager user ID of this evp employee
	 */
	public void setManagerUserId(long managerUserId);

	/**
	 * Returns the manager user uuid of this evp employee.
	 *
	 * @return the manager user uuid of this evp employee
	 */
	public String getManagerUserUuid();

	/**
	 * Sets the manager user uuid of this evp employee.
	 *
	 * @param managerUserUuid the manager user uuid of this evp employee
	 */
	public void setManagerUserUuid(String managerUserUuid);

	/**
	 * Returns the subsidiary evp division ID of this evp employee.
	 *
	 * @return the subsidiary evp division ID of this evp employee
	 */
	public long getSubsidiaryEVPDivisionId();

	/**
	 * Sets the subsidiary evp division ID of this evp employee.
	 *
	 * @param subsidiaryEVPDivisionId the subsidiary evp division ID of this evp employee
	 */
	public void setSubsidiaryEVPDivisionId(long subsidiaryEVPDivisionId);

	/**
	 * Returns the employment type of this evp employee.
	 *
	 * @return the employment type of this evp employee
	 */
	public int getEmploymentType();

	/**
	 * Sets the employment type of this evp employee.
	 *
	 * @param employmentType the employment type of this evp employee
	 */
	public void setEmploymentType(int employmentType);

	/**
	 * Returns the hire date of this evp employee.
	 *
	 * @return the hire date of this evp employee
	 */
	public Date getHireDate();

	/**
	 * Sets the hire date of this evp employee.
	 *
	 * @param hireDate the hire date of this evp employee
	 */
	public void setHireDate(Date hireDate);

}