/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EVPKaleoForkInstance service. Represents a row in the &quot;EVPKaleoForkInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.evp.model.impl.EVPKaleoForkInstanceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.evp.model.impl.EVPKaleoForkInstanceImpl</code>.
 * </p>
 *
 * @author Val Nagy
 * @see EVPKaleoForkInstance
 * @generated
 */
@ProviderType
public interface EVPKaleoForkInstanceModel
	extends AttachedModel, AuditedModel, BaseModel<EVPKaleoForkInstance>,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evp kaleo fork instance model instance should use the {@link EVPKaleoForkInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this evp kaleo fork instance.
	 *
	 * @return the primary key of this evp kaleo fork instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this evp kaleo fork instance.
	 *
	 * @param primaryKey the primary key of this evp kaleo fork instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evp kaleo fork instance ID of this evp kaleo fork instance.
	 *
	 * @return the evp kaleo fork instance ID of this evp kaleo fork instance
	 */
	public long getEvpKaleoForkInstanceId();

	/**
	 * Sets the evp kaleo fork instance ID of this evp kaleo fork instance.
	 *
	 * @param evpKaleoForkInstanceId the evp kaleo fork instance ID of this evp kaleo fork instance
	 */
	public void setEvpKaleoForkInstanceId(long evpKaleoForkInstanceId);

	/**
	 * Returns the company ID of this evp kaleo fork instance.
	 *
	 * @return the company ID of this evp kaleo fork instance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this evp kaleo fork instance.
	 *
	 * @param companyId the company ID of this evp kaleo fork instance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this evp kaleo fork instance.
	 *
	 * @return the user ID of this evp kaleo fork instance
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this evp kaleo fork instance.
	 *
	 * @param userId the user ID of this evp kaleo fork instance
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this evp kaleo fork instance.
	 *
	 * @return the user uuid of this evp kaleo fork instance
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this evp kaleo fork instance.
	 *
	 * @param userUuid the user uuid of this evp kaleo fork instance
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this evp kaleo fork instance.
	 *
	 * @return the user name of this evp kaleo fork instance
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this evp kaleo fork instance.
	 *
	 * @param userName the user name of this evp kaleo fork instance
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this evp kaleo fork instance.
	 *
	 * @return the create date of this evp kaleo fork instance
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this evp kaleo fork instance.
	 *
	 * @param createDate the create date of this evp kaleo fork instance
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this evp kaleo fork instance.
	 *
	 * @return the modified date of this evp kaleo fork instance
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this evp kaleo fork instance.
	 *
	 * @param modifiedDate the modified date of this evp kaleo fork instance
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this evp kaleo fork instance.
	 *
	 * @return the fully qualified class name of this evp kaleo fork instance
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this evp kaleo fork instance.
	 *
	 * @return the class name ID of this evp kaleo fork instance
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this evp kaleo fork instance.
	 *
	 * @param classNameId the class name ID of this evp kaleo fork instance
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this evp kaleo fork instance.
	 *
	 * @return the class pk of this evp kaleo fork instance
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this evp kaleo fork instance.
	 *
	 * @param classPK the class pk of this evp kaleo fork instance
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the type of this evp kaleo fork instance.
	 *
	 * @return the type of this evp kaleo fork instance
	 */
	public int getType();

	/**
	 * Sets the type of this evp kaleo fork instance.
	 *
	 * @param type the type of this evp kaleo fork instance
	 */
	public void setType(int type);

	/**
	 * Returns the status of this evp kaleo fork instance.
	 *
	 * @return the status of this evp kaleo fork instance
	 */
	public int getStatus();

	/**
	 * Sets the status of this evp kaleo fork instance.
	 *
	 * @param status the status of this evp kaleo fork instance
	 */
	public void setStatus(int status);

}