/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.evp.model.impl;

import com.liferay.evp.model.EVPServiceRequest;
import com.liferay.evp.model.EVPServiceRequestModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.PortalUtil;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EVPServiceRequest service. Represents a row in the &quot;EVPServiceRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.evp.model.EVPServiceRequestModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EVPServiceRequestImpl}.
 * </p>
 *
 * @author Val Nagy
 * @see EVPServiceRequestImpl
 * @see com.liferay.evp.model.EVPServiceRequest
 * @see com.liferay.evp.model.EVPServiceRequestModel
 * @generated
 */
public class EVPServiceRequestModelImpl extends BaseModelImpl<EVPServiceRequest>
	implements EVPServiceRequestModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e v p service request model instance should use the {@link com.liferay.evp.model.EVPServiceRequest} interface instead.
	 */
	public static final String TABLE_NAME = "EVPServiceRequest";
	public static final Object[][] TABLE_COLUMNS = {
			{ "evpServiceRequestId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "contactEmailAddressId", Types.BIGINT },
			{ "contactPhoneId", Types.BIGINT },
			{ "contactUserId", Types.BIGINT },
			{ "evpRequestOrganizationId", Types.BIGINT },
			{ "managerUserId", Types.BIGINT },
			{ "parentEVPServiceRequestId", Types.BIGINT },
			{ "requestOrganizationAddressId", Types.BIGINT },
			{ "requestOrganizationWebsiteId", Types.BIGINT },
			{ "subsidiaryGroupId", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "employmentType", Types.INTEGER },
			{ "employmentHoursPerWeek", Types.INTEGER },
			{ "purpose", Types.VARCHAR },
			{ "purposeOther", Types.VARCHAR },
			{ "behalfOf", Types.VARCHAR },
			{ "behalfOfOther", Types.VARCHAR },
			{ "requestedStartDate", Types.TIMESTAMP },
			{ "requestedEndDate", Types.TIMESTAMP },
			{ "requestedTotalHours", Types.INTEGER },
			{ "promoteTrip", Types.BOOLEAN },
			{ "confirmedStartDate", Types.TIMESTAMP },
			{ "confirmedEndDate", Types.TIMESTAMP },
			{ "confirmedTotalHours", Types.INTEGER },
			{ "contactBenefit", Types.VARCHAR },
			{ "contactComments", Types.VARCHAR },
			{ "hash", Types.VARCHAR },
			{ "feedbackDescription", Types.VARCHAR },
			{ "employeeBenefit", Types.VARCHAR },
			{ "recipientBenefit", Types.VARCHAR },
			{ "shareStory", Types.BOOLEAN },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table EVPServiceRequest (evpServiceRequestId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(128) null,createDate DATE null,modifiedDate DATE null,contactEmailAddressId LONG,contactPhoneId LONG,contactUserId LONG,evpRequestOrganizationId LONG,managerUserId LONG,parentEVPServiceRequestId LONG,requestOrganizationAddressId LONG,requestOrganizationWebsiteId LONG,subsidiaryGroupId LONG,description STRING null,employmentType INTEGER,employmentHoursPerWeek INTEGER,purpose VARCHAR(128) null,purposeOther VARCHAR(128) null,behalfOf VARCHAR(128) null,behalfOfOther VARCHAR(128) null,requestedStartDate DATE null,requestedEndDate DATE null,requestedTotalHours INTEGER,promoteTrip BOOLEAN,confirmedStartDate DATE null,confirmedEndDate DATE null,confirmedTotalHours INTEGER,contactBenefit STRING null,contactComments STRING null,hash VARCHAR(128) null,feedbackDescription STRING null,employeeBenefit STRING null,recipientBenefit STRING null,shareStory BOOLEAN,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(128) null,statusDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table EVPServiceRequest";
	public static final String ORDER_BY_JPQL = " ORDER BY evpServiceRequest.evpServiceRequestId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EVPServiceRequest.evpServiceRequestId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.evp.model.EVPServiceRequest"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.evp.model.EVPServiceRequest"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.evp.model.EVPServiceRequest"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long STATUS_COLUMN_BITMASK = 2L;
	public static long EVPSERVICEREQUESTID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.evp.model.EVPServiceRequest"));

	public EVPServiceRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _evpServiceRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEvpServiceRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _evpServiceRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EVPServiceRequest.class;
	}

	@Override
	public String getModelClassName() {
		return EVPServiceRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("evpServiceRequestId", getEvpServiceRequestId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("contactEmailAddressId", getContactEmailAddressId());
		attributes.put("contactPhoneId", getContactPhoneId());
		attributes.put("contactUserId", getContactUserId());
		attributes.put("evpRequestOrganizationId", getEvpRequestOrganizationId());
		attributes.put("managerUserId", getManagerUserId());
		attributes.put("parentEVPServiceRequestId",
			getParentEVPServiceRequestId());
		attributes.put("requestOrganizationAddressId",
			getRequestOrganizationAddressId());
		attributes.put("requestOrganizationWebsiteId",
			getRequestOrganizationWebsiteId());
		attributes.put("subsidiaryGroupId", getSubsidiaryGroupId());
		attributes.put("description", getDescription());
		attributes.put("employmentType", getEmploymentType());
		attributes.put("employmentHoursPerWeek", getEmploymentHoursPerWeek());
		attributes.put("purpose", getPurpose());
		attributes.put("purposeOther", getPurposeOther());
		attributes.put("behalfOf", getBehalfOf());
		attributes.put("behalfOfOther", getBehalfOfOther());
		attributes.put("requestedStartDate", getRequestedStartDate());
		attributes.put("requestedEndDate", getRequestedEndDate());
		attributes.put("requestedTotalHours", getRequestedTotalHours());
		attributes.put("promoteTrip", getPromoteTrip());
		attributes.put("confirmedStartDate", getConfirmedStartDate());
		attributes.put("confirmedEndDate", getConfirmedEndDate());
		attributes.put("confirmedTotalHours", getConfirmedTotalHours());
		attributes.put("contactBenefit", getContactBenefit());
		attributes.put("contactComments", getContactComments());
		attributes.put("hash", getHash());
		attributes.put("feedbackDescription", getFeedbackDescription());
		attributes.put("employeeBenefit", getEmployeeBenefit());
		attributes.put("recipientBenefit", getRecipientBenefit());
		attributes.put("shareStory", getShareStory());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long evpServiceRequestId = (Long)attributes.get("evpServiceRequestId");

		if (evpServiceRequestId != null) {
			setEvpServiceRequestId(evpServiceRequestId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long contactEmailAddressId = (Long)attributes.get(
				"contactEmailAddressId");

		if (contactEmailAddressId != null) {
			setContactEmailAddressId(contactEmailAddressId);
		}

		Long contactPhoneId = (Long)attributes.get("contactPhoneId");

		if (contactPhoneId != null) {
			setContactPhoneId(contactPhoneId);
		}

		Long contactUserId = (Long)attributes.get("contactUserId");

		if (contactUserId != null) {
			setContactUserId(contactUserId);
		}

		Long evpRequestOrganizationId = (Long)attributes.get(
				"evpRequestOrganizationId");

		if (evpRequestOrganizationId != null) {
			setEvpRequestOrganizationId(evpRequestOrganizationId);
		}

		Long managerUserId = (Long)attributes.get("managerUserId");

		if (managerUserId != null) {
			setManagerUserId(managerUserId);
		}

		Long parentEVPServiceRequestId = (Long)attributes.get(
				"parentEVPServiceRequestId");

		if (parentEVPServiceRequestId != null) {
			setParentEVPServiceRequestId(parentEVPServiceRequestId);
		}

		Long requestOrganizationAddressId = (Long)attributes.get(
				"requestOrganizationAddressId");

		if (requestOrganizationAddressId != null) {
			setRequestOrganizationAddressId(requestOrganizationAddressId);
		}

		Long requestOrganizationWebsiteId = (Long)attributes.get(
				"requestOrganizationWebsiteId");

		if (requestOrganizationWebsiteId != null) {
			setRequestOrganizationWebsiteId(requestOrganizationWebsiteId);
		}

		Long subsidiaryGroupId = (Long)attributes.get("subsidiaryGroupId");

		if (subsidiaryGroupId != null) {
			setSubsidiaryGroupId(subsidiaryGroupId);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Integer employmentType = (Integer)attributes.get("employmentType");

		if (employmentType != null) {
			setEmploymentType(employmentType);
		}

		Integer employmentHoursPerWeek = (Integer)attributes.get(
				"employmentHoursPerWeek");

		if (employmentHoursPerWeek != null) {
			setEmploymentHoursPerWeek(employmentHoursPerWeek);
		}

		String purpose = (String)attributes.get("purpose");

		if (purpose != null) {
			setPurpose(purpose);
		}

		String purposeOther = (String)attributes.get("purposeOther");

		if (purposeOther != null) {
			setPurposeOther(purposeOther);
		}

		String behalfOf = (String)attributes.get("behalfOf");

		if (behalfOf != null) {
			setBehalfOf(behalfOf);
		}

		String behalfOfOther = (String)attributes.get("behalfOfOther");

		if (behalfOfOther != null) {
			setBehalfOfOther(behalfOfOther);
		}

		Date requestedStartDate = (Date)attributes.get("requestedStartDate");

		if (requestedStartDate != null) {
			setRequestedStartDate(requestedStartDate);
		}

		Date requestedEndDate = (Date)attributes.get("requestedEndDate");

		if (requestedEndDate != null) {
			setRequestedEndDate(requestedEndDate);
		}

		Integer requestedTotalHours = (Integer)attributes.get(
				"requestedTotalHours");

		if (requestedTotalHours != null) {
			setRequestedTotalHours(requestedTotalHours);
		}

		Boolean promoteTrip = (Boolean)attributes.get("promoteTrip");

		if (promoteTrip != null) {
			setPromoteTrip(promoteTrip);
		}

		Date confirmedStartDate = (Date)attributes.get("confirmedStartDate");

		if (confirmedStartDate != null) {
			setConfirmedStartDate(confirmedStartDate);
		}

		Date confirmedEndDate = (Date)attributes.get("confirmedEndDate");

		if (confirmedEndDate != null) {
			setConfirmedEndDate(confirmedEndDate);
		}

		Integer confirmedTotalHours = (Integer)attributes.get(
				"confirmedTotalHours");

		if (confirmedTotalHours != null) {
			setConfirmedTotalHours(confirmedTotalHours);
		}

		String contactBenefit = (String)attributes.get("contactBenefit");

		if (contactBenefit != null) {
			setContactBenefit(contactBenefit);
		}

		String contactComments = (String)attributes.get("contactComments");

		if (contactComments != null) {
			setContactComments(contactComments);
		}

		String hash = (String)attributes.get("hash");

		if (hash != null) {
			setHash(hash);
		}

		String feedbackDescription = (String)attributes.get(
				"feedbackDescription");

		if (feedbackDescription != null) {
			setFeedbackDescription(feedbackDescription);
		}

		String employeeBenefit = (String)attributes.get("employeeBenefit");

		if (employeeBenefit != null) {
			setEmployeeBenefit(employeeBenefit);
		}

		String recipientBenefit = (String)attributes.get("recipientBenefit");

		if (recipientBenefit != null) {
			setRecipientBenefit(recipientBenefit);
		}

		Boolean shareStory = (Boolean)attributes.get("shareStory");

		if (shareStory != null) {
			setShareStory(shareStory);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}
	}

	@Override
	public long getEvpServiceRequestId() {
		return _evpServiceRequestId;
	}

	@Override
	public void setEvpServiceRequestId(long evpServiceRequestId) {
		_evpServiceRequestId = evpServiceRequestId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid); // FIXME: @deprecated As of Wilberforce (7.0.x), with no direct replacement // FIXME: @deprecated As of Wilberforce (7.0.x), with no direct replacement
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getContactEmailAddressId() {
		return _contactEmailAddressId;
	}

	@Override
	public void setContactEmailAddressId(long contactEmailAddressId) {
		_contactEmailAddressId = contactEmailAddressId;
	}

	@Override
	public long getContactPhoneId() {
		return _contactPhoneId;
	}

	@Override
	public void setContactPhoneId(long contactPhoneId) {
		_contactPhoneId = contactPhoneId;
	}

	@Override
	public long getContactUserId() {
		return _contactUserId;
	}

	@Override
	public void setContactUserId(long contactUserId) {
		_contactUserId = contactUserId;
	}

	@Override
	public String getContactUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getContactUserId(), "uuid", // FIXME: @deprecated As of Wilberforce (7.0.x), with no direct replacement // FIXME: @deprecated As of Wilberforce (7.0.x), with no direct replacement
			_contactUserUuid);
	}

	@Override
	public void setContactUserUuid(String contactUserUuid) {
		_contactUserUuid = contactUserUuid;
	}

	@Override
	public long getEvpRequestOrganizationId() {
		return _evpRequestOrganizationId;
	}

	@Override
	public void setEvpRequestOrganizationId(long evpRequestOrganizationId) {
		_evpRequestOrganizationId = evpRequestOrganizationId;
	}

	@Override
	public long getManagerUserId() {
		return _managerUserId;
	}

	@Override
	public void setManagerUserId(long managerUserId) {
		_managerUserId = managerUserId;
	}

	@Override
	public String getManagerUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getManagerUserId(), "uuid", // FIXME: @deprecated As of Wilberforce (7.0.x), with no direct replacement // FIXME: @deprecated As of Wilberforce (7.0.x), with no direct replacement
			_managerUserUuid);
	}

	@Override
	public void setManagerUserUuid(String managerUserUuid) {
		_managerUserUuid = managerUserUuid;
	}

	@Override
	public long getParentEVPServiceRequestId() {
		return _parentEVPServiceRequestId;
	}

	@Override
	public void setParentEVPServiceRequestId(long parentEVPServiceRequestId) {
		_parentEVPServiceRequestId = parentEVPServiceRequestId;
	}

	@Override
	public long getRequestOrganizationAddressId() {
		return _requestOrganizationAddressId;
	}

	@Override
	public void setRequestOrganizationAddressId(
		long requestOrganizationAddressId) {
		_requestOrganizationAddressId = requestOrganizationAddressId;
	}

	@Override
	public long getRequestOrganizationWebsiteId() {
		return _requestOrganizationWebsiteId;
	}

	@Override
	public void setRequestOrganizationWebsiteId(
		long requestOrganizationWebsiteId) {
		_requestOrganizationWebsiteId = requestOrganizationWebsiteId;
	}

	@Override
	public long getSubsidiaryGroupId() {
		return _subsidiaryGroupId;
	}

	@Override
	public void setSubsidiaryGroupId(long subsidiaryGroupId) {
		_subsidiaryGroupId = subsidiaryGroupId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public int getEmploymentType() {
		return _employmentType;
	}

	@Override
	public void setEmploymentType(int employmentType) {
		_employmentType = employmentType;
	}

	@Override
	public int getEmploymentHoursPerWeek() {
		return _employmentHoursPerWeek;
	}

	@Override
	public void setEmploymentHoursPerWeek(int employmentHoursPerWeek) {
		_employmentHoursPerWeek = employmentHoursPerWeek;
	}

	@Override
	public String getPurpose() {
		if (_purpose == null) {
			return StringPool.BLANK;
		}
		else {
			return _purpose;
		}
	}

	@Override
	public void setPurpose(String purpose) {
		_purpose = purpose;
	}

	@Override
	public String getPurposeOther() {
		if (_purposeOther == null) {
			return StringPool.BLANK;
		}
		else {
			return _purposeOther;
		}
	}

	@Override
	public void setPurposeOther(String purposeOther) {
		_purposeOther = purposeOther;
	}

	@Override
	public String getBehalfOf() {
		if (_behalfOf == null) {
			return StringPool.BLANK;
		}
		else {
			return _behalfOf;
		}
	}

	@Override
	public void setBehalfOf(String behalfOf) {
		_behalfOf = behalfOf;
	}

	@Override
	public String getBehalfOfOther() {
		if (_behalfOfOther == null) {
			return StringPool.BLANK;
		}
		else {
			return _behalfOfOther;
		}
	}

	@Override
	public void setBehalfOfOther(String behalfOfOther) {
		_behalfOfOther = behalfOfOther;
	}

	@Override
	public Date getRequestedStartDate() {
		return _requestedStartDate;
	}

	@Override
	public void setRequestedStartDate(Date requestedStartDate) {
		_requestedStartDate = requestedStartDate;
	}

	@Override
	public Date getRequestedEndDate() {
		return _requestedEndDate;
	}

	@Override
	public void setRequestedEndDate(Date requestedEndDate) {
		_requestedEndDate = requestedEndDate;
	}

	@Override
	public int getRequestedTotalHours() {
		return _requestedTotalHours;
	}

	@Override
	public void setRequestedTotalHours(int requestedTotalHours) {
		_requestedTotalHours = requestedTotalHours;
	}

	@Override
	public boolean getPromoteTrip() {
		return _promoteTrip;
	}

	@Override
	public boolean isPromoteTrip() {
		return _promoteTrip;
	}

	@Override
	public void setPromoteTrip(boolean promoteTrip) {
		_promoteTrip = promoteTrip;
	}

	@Override
	public Date getConfirmedStartDate() {
		return _confirmedStartDate;
	}

	@Override
	public void setConfirmedStartDate(Date confirmedStartDate) {
		_confirmedStartDate = confirmedStartDate;
	}

	@Override
	public Date getConfirmedEndDate() {
		return _confirmedEndDate;
	}

	@Override
	public void setConfirmedEndDate(Date confirmedEndDate) {
		_confirmedEndDate = confirmedEndDate;
	}

	@Override
	public int getConfirmedTotalHours() {
		return _confirmedTotalHours;
	}

	@Override
	public void setConfirmedTotalHours(int confirmedTotalHours) {
		_confirmedTotalHours = confirmedTotalHours;
	}

	@Override
	public String getContactBenefit() {
		if (_contactBenefit == null) {
			return StringPool.BLANK;
		}
		else {
			return _contactBenefit;
		}
	}

	@Override
	public void setContactBenefit(String contactBenefit) {
		_contactBenefit = contactBenefit;
	}

	@Override
	public String getContactComments() {
		if (_contactComments == null) {
			return StringPool.BLANK;
		}
		else {
			return _contactComments;
		}
	}

	@Override
	public void setContactComments(String contactComments) {
		_contactComments = contactComments;
	}

	@Override
	public String getHash() {
		if (_hash == null) {
			return StringPool.BLANK;
		}
		else {
			return _hash;
		}
	}

	@Override
	public void setHash(String hash) {
		_hash = hash;
	}

	@Override
	public String getFeedbackDescription() {
		if (_feedbackDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _feedbackDescription;
		}
	}

	@Override
	public void setFeedbackDescription(String feedbackDescription) {
		_feedbackDescription = feedbackDescription;
	}

	@Override
	public String getEmployeeBenefit() {
		if (_employeeBenefit == null) {
			return StringPool.BLANK;
		}
		else {
			return _employeeBenefit;
		}
	}

	@Override
	public void setEmployeeBenefit(String employeeBenefit) {
		_employeeBenefit = employeeBenefit;
	}

	@Override
	public String getRecipientBenefit() {
		if (_recipientBenefit == null) {
			return StringPool.BLANK;
		}
		else {
			return _recipientBenefit;
		}
	}

	@Override
	public void setRecipientBenefit(String recipientBenefit) {
		_recipientBenefit = recipientBenefit;
	}

	@Override
	public boolean getShareStory() {
		return _shareStory;
	}

	@Override
	public boolean isShareStory() {
		return _shareStory;
	}

	@Override
	public void setShareStory(boolean shareStory) {
		_shareStory = shareStory;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStatusByUserId(), "uuid", // FIXME: @deprecated As of Wilberforce (7.0.x), with no direct replacement // FIXME: @deprecated As of Wilberforce (7.0.x), with no direct replacement
			_statusByUserUuid);
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
		_statusByUserUuid = statusByUserUuid;
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved}
	 */
	@Override
	public boolean getApproved() {
		return isApproved();
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EVPServiceRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EVPServiceRequest toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EVPServiceRequest)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EVPServiceRequestImpl evpServiceRequestImpl = new EVPServiceRequestImpl();

		evpServiceRequestImpl.setEvpServiceRequestId(getEvpServiceRequestId());
		evpServiceRequestImpl.setCompanyId(getCompanyId());
		evpServiceRequestImpl.setUserId(getUserId());
		evpServiceRequestImpl.setUserName(getUserName());
		evpServiceRequestImpl.setCreateDate(getCreateDate());
		evpServiceRequestImpl.setModifiedDate(getModifiedDate());
		evpServiceRequestImpl.setContactEmailAddressId(getContactEmailAddressId());
		evpServiceRequestImpl.setContactPhoneId(getContactPhoneId());
		evpServiceRequestImpl.setContactUserId(getContactUserId());
		evpServiceRequestImpl.setEvpRequestOrganizationId(getEvpRequestOrganizationId());
		evpServiceRequestImpl.setManagerUserId(getManagerUserId());
		evpServiceRequestImpl.setParentEVPServiceRequestId(getParentEVPServiceRequestId());
		evpServiceRequestImpl.setRequestOrganizationAddressId(getRequestOrganizationAddressId());
		evpServiceRequestImpl.setRequestOrganizationWebsiteId(getRequestOrganizationWebsiteId());
		evpServiceRequestImpl.setSubsidiaryGroupId(getSubsidiaryGroupId());
		evpServiceRequestImpl.setDescription(getDescription());
		evpServiceRequestImpl.setEmploymentType(getEmploymentType());
		evpServiceRequestImpl.setEmploymentHoursPerWeek(getEmploymentHoursPerWeek());
		evpServiceRequestImpl.setPurpose(getPurpose());
		evpServiceRequestImpl.setPurposeOther(getPurposeOther());
		evpServiceRequestImpl.setBehalfOf(getBehalfOf());
		evpServiceRequestImpl.setBehalfOfOther(getBehalfOfOther());
		evpServiceRequestImpl.setRequestedStartDate(getRequestedStartDate());
		evpServiceRequestImpl.setRequestedEndDate(getRequestedEndDate());
		evpServiceRequestImpl.setRequestedTotalHours(getRequestedTotalHours());
		evpServiceRequestImpl.setPromoteTrip(getPromoteTrip());
		evpServiceRequestImpl.setConfirmedStartDate(getConfirmedStartDate());
		evpServiceRequestImpl.setConfirmedEndDate(getConfirmedEndDate());
		evpServiceRequestImpl.setConfirmedTotalHours(getConfirmedTotalHours());
		evpServiceRequestImpl.setContactBenefit(getContactBenefit());
		evpServiceRequestImpl.setContactComments(getContactComments());
		evpServiceRequestImpl.setHash(getHash());
		evpServiceRequestImpl.setFeedbackDescription(getFeedbackDescription());
		evpServiceRequestImpl.setEmployeeBenefit(getEmployeeBenefit());
		evpServiceRequestImpl.setRecipientBenefit(getRecipientBenefit());
		evpServiceRequestImpl.setShareStory(getShareStory());
		evpServiceRequestImpl.setStatus(getStatus());
		evpServiceRequestImpl.setStatusByUserId(getStatusByUserId());
		evpServiceRequestImpl.setStatusByUserName(getStatusByUserName());
		evpServiceRequestImpl.setStatusDate(getStatusDate());

		evpServiceRequestImpl.resetOriginalValues();

		return evpServiceRequestImpl;
	}

	@Override
	public int compareTo(EVPServiceRequest evpServiceRequest) {
		long primaryKey = evpServiceRequest.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EVPServiceRequest)) {
			return false;
		}

		EVPServiceRequest evpServiceRequest = (EVPServiceRequest)obj;

		long primaryKey = evpServiceRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EVPServiceRequestModelImpl evpServiceRequestModelImpl = this;

		evpServiceRequestModelImpl._originalCompanyId = evpServiceRequestModelImpl._companyId;

		evpServiceRequestModelImpl._setOriginalCompanyId = false;

		evpServiceRequestModelImpl._originalStatus = evpServiceRequestModelImpl._status;

		evpServiceRequestModelImpl._setOriginalStatus = false;

		evpServiceRequestModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EVPServiceRequest> toCacheModel() {
		EVPServiceRequestCacheModel evpServiceRequestCacheModel = new EVPServiceRequestCacheModel();

		evpServiceRequestCacheModel.evpServiceRequestId = getEvpServiceRequestId();

		evpServiceRequestCacheModel.companyId = getCompanyId();

		evpServiceRequestCacheModel.userId = getUserId();

		evpServiceRequestCacheModel.userName = getUserName();

		String userName = evpServiceRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			evpServiceRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			evpServiceRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			evpServiceRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			evpServiceRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			evpServiceRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		evpServiceRequestCacheModel.contactEmailAddressId = getContactEmailAddressId();

		evpServiceRequestCacheModel.contactPhoneId = getContactPhoneId();

		evpServiceRequestCacheModel.contactUserId = getContactUserId();

		evpServiceRequestCacheModel.evpRequestOrganizationId = getEvpRequestOrganizationId();

		evpServiceRequestCacheModel.managerUserId = getManagerUserId();

		evpServiceRequestCacheModel.parentEVPServiceRequestId = getParentEVPServiceRequestId();

		evpServiceRequestCacheModel.requestOrganizationAddressId = getRequestOrganizationAddressId();

		evpServiceRequestCacheModel.requestOrganizationWebsiteId = getRequestOrganizationWebsiteId();

		evpServiceRequestCacheModel.subsidiaryGroupId = getSubsidiaryGroupId();

		evpServiceRequestCacheModel.description = getDescription();

		String description = evpServiceRequestCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			evpServiceRequestCacheModel.description = null;
		}

		evpServiceRequestCacheModel.employmentType = getEmploymentType();

		evpServiceRequestCacheModel.employmentHoursPerWeek = getEmploymentHoursPerWeek();

		evpServiceRequestCacheModel.purpose = getPurpose();

		String purpose = evpServiceRequestCacheModel.purpose;

		if ((purpose != null) && (purpose.length() == 0)) {
			evpServiceRequestCacheModel.purpose = null;
		}

		evpServiceRequestCacheModel.purposeOther = getPurposeOther();

		String purposeOther = evpServiceRequestCacheModel.purposeOther;

		if ((purposeOther != null) && (purposeOther.length() == 0)) {
			evpServiceRequestCacheModel.purposeOther = null;
		}

		evpServiceRequestCacheModel.behalfOf = getBehalfOf();

		String behalfOf = evpServiceRequestCacheModel.behalfOf;

		if ((behalfOf != null) && (behalfOf.length() == 0)) {
			evpServiceRequestCacheModel.behalfOf = null;
		}

		evpServiceRequestCacheModel.behalfOfOther = getBehalfOfOther();

		String behalfOfOther = evpServiceRequestCacheModel.behalfOfOther;

		if ((behalfOfOther != null) && (behalfOfOther.length() == 0)) {
			evpServiceRequestCacheModel.behalfOfOther = null;
		}

		Date requestedStartDate = getRequestedStartDate();

		if (requestedStartDate != null) {
			evpServiceRequestCacheModel.requestedStartDate = requestedStartDate.getTime();
		}
		else {
			evpServiceRequestCacheModel.requestedStartDate = Long.MIN_VALUE;
		}

		Date requestedEndDate = getRequestedEndDate();

		if (requestedEndDate != null) {
			evpServiceRequestCacheModel.requestedEndDate = requestedEndDate.getTime();
		}
		else {
			evpServiceRequestCacheModel.requestedEndDate = Long.MIN_VALUE;
		}

		evpServiceRequestCacheModel.requestedTotalHours = getRequestedTotalHours();

		evpServiceRequestCacheModel.promoteTrip = getPromoteTrip();

		Date confirmedStartDate = getConfirmedStartDate();

		if (confirmedStartDate != null) {
			evpServiceRequestCacheModel.confirmedStartDate = confirmedStartDate.getTime();
		}
		else {
			evpServiceRequestCacheModel.confirmedStartDate = Long.MIN_VALUE;
		}

		Date confirmedEndDate = getConfirmedEndDate();

		if (confirmedEndDate != null) {
			evpServiceRequestCacheModel.confirmedEndDate = confirmedEndDate.getTime();
		}
		else {
			evpServiceRequestCacheModel.confirmedEndDate = Long.MIN_VALUE;
		}

		evpServiceRequestCacheModel.confirmedTotalHours = getConfirmedTotalHours();

		evpServiceRequestCacheModel.contactBenefit = getContactBenefit();

		String contactBenefit = evpServiceRequestCacheModel.contactBenefit;

		if ((contactBenefit != null) && (contactBenefit.length() == 0)) {
			evpServiceRequestCacheModel.contactBenefit = null;
		}

		evpServiceRequestCacheModel.contactComments = getContactComments();

		String contactComments = evpServiceRequestCacheModel.contactComments;

		if ((contactComments != null) && (contactComments.length() == 0)) {
			evpServiceRequestCacheModel.contactComments = null;
		}

		evpServiceRequestCacheModel.hash = getHash();

		String hash = evpServiceRequestCacheModel.hash;

		if ((hash != null) && (hash.length() == 0)) {
			evpServiceRequestCacheModel.hash = null;
		}

		evpServiceRequestCacheModel.feedbackDescription = getFeedbackDescription();

		String feedbackDescription = evpServiceRequestCacheModel.feedbackDescription;

		if ((feedbackDescription != null) &&
				(feedbackDescription.length() == 0)) {
			evpServiceRequestCacheModel.feedbackDescription = null;
		}

		evpServiceRequestCacheModel.employeeBenefit = getEmployeeBenefit();

		String employeeBenefit = evpServiceRequestCacheModel.employeeBenefit;

		if ((employeeBenefit != null) && (employeeBenefit.length() == 0)) {
			evpServiceRequestCacheModel.employeeBenefit = null;
		}

		evpServiceRequestCacheModel.recipientBenefit = getRecipientBenefit();

		String recipientBenefit = evpServiceRequestCacheModel.recipientBenefit;

		if ((recipientBenefit != null) && (recipientBenefit.length() == 0)) {
			evpServiceRequestCacheModel.recipientBenefit = null;
		}

		evpServiceRequestCacheModel.shareStory = getShareStory();

		evpServiceRequestCacheModel.status = getStatus();

		evpServiceRequestCacheModel.statusByUserId = getStatusByUserId();

		evpServiceRequestCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = evpServiceRequestCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			evpServiceRequestCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			evpServiceRequestCacheModel.statusDate = statusDate.getTime();
		}
		else {
			evpServiceRequestCacheModel.statusDate = Long.MIN_VALUE;
		}

		return evpServiceRequestCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(81);

		sb.append("{evpServiceRequestId=");
		sb.append(getEvpServiceRequestId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", contactEmailAddressId=");
		sb.append(getContactEmailAddressId());
		sb.append(", contactPhoneId=");
		sb.append(getContactPhoneId());
		sb.append(", contactUserId=");
		sb.append(getContactUserId());
		sb.append(", evpRequestOrganizationId=");
		sb.append(getEvpRequestOrganizationId());
		sb.append(", managerUserId=");
		sb.append(getManagerUserId());
		sb.append(", parentEVPServiceRequestId=");
		sb.append(getParentEVPServiceRequestId());
		sb.append(", requestOrganizationAddressId=");
		sb.append(getRequestOrganizationAddressId());
		sb.append(", requestOrganizationWebsiteId=");
		sb.append(getRequestOrganizationWebsiteId());
		sb.append(", subsidiaryGroupId=");
		sb.append(getSubsidiaryGroupId());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", employmentType=");
		sb.append(getEmploymentType());
		sb.append(", employmentHoursPerWeek=");
		sb.append(getEmploymentHoursPerWeek());
		sb.append(", purpose=");
		sb.append(getPurpose());
		sb.append(", purposeOther=");
		sb.append(getPurposeOther());
		sb.append(", behalfOf=");
		sb.append(getBehalfOf());
		sb.append(", behalfOfOther=");
		sb.append(getBehalfOfOther());
		sb.append(", requestedStartDate=");
		sb.append(getRequestedStartDate());
		sb.append(", requestedEndDate=");
		sb.append(getRequestedEndDate());
		sb.append(", requestedTotalHours=");
		sb.append(getRequestedTotalHours());
		sb.append(", promoteTrip=");
		sb.append(getPromoteTrip());
		sb.append(", confirmedStartDate=");
		sb.append(getConfirmedStartDate());
		sb.append(", confirmedEndDate=");
		sb.append(getConfirmedEndDate());
		sb.append(", confirmedTotalHours=");
		sb.append(getConfirmedTotalHours());
		sb.append(", contactBenefit=");
		sb.append(getContactBenefit());
		sb.append(", contactComments=");
		sb.append(getContactComments());
		sb.append(", hash=");
		sb.append(getHash());
		sb.append(", feedbackDescription=");
		sb.append(getFeedbackDescription());
		sb.append(", employeeBenefit=");
		sb.append(getEmployeeBenefit());
		sb.append(", recipientBenefit=");
		sb.append(getRecipientBenefit());
		sb.append(", shareStory=");
		sb.append(getShareStory());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(124);

		sb.append("<model><model-name>");
		sb.append("com.liferay.evp.model.EVPServiceRequest");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>evpServiceRequestId</column-name><column-value><![CDATA[");
		sb.append(getEvpServiceRequestId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactEmailAddressId</column-name><column-value><![CDATA[");
		sb.append(getContactEmailAddressId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactPhoneId</column-name><column-value><![CDATA[");
		sb.append(getContactPhoneId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactUserId</column-name><column-value><![CDATA[");
		sb.append(getContactUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>evpRequestOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getEvpRequestOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>managerUserId</column-name><column-value><![CDATA[");
		sb.append(getManagerUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentEVPServiceRequestId</column-name><column-value><![CDATA[");
		sb.append(getParentEVPServiceRequestId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestOrganizationAddressId</column-name><column-value><![CDATA[");
		sb.append(getRequestOrganizationAddressId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestOrganizationWebsiteId</column-name><column-value><![CDATA[");
		sb.append(getRequestOrganizationWebsiteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subsidiaryGroupId</column-name><column-value><![CDATA[");
		sb.append(getSubsidiaryGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employmentType</column-name><column-value><![CDATA[");
		sb.append(getEmploymentType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employmentHoursPerWeek</column-name><column-value><![CDATA[");
		sb.append(getEmploymentHoursPerWeek());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>purpose</column-name><column-value><![CDATA[");
		sb.append(getPurpose());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>purposeOther</column-name><column-value><![CDATA[");
		sb.append(getPurposeOther());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>behalfOf</column-name><column-value><![CDATA[");
		sb.append(getBehalfOf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>behalfOfOther</column-name><column-value><![CDATA[");
		sb.append(getBehalfOfOther());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestedStartDate</column-name><column-value><![CDATA[");
		sb.append(getRequestedStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestedEndDate</column-name><column-value><![CDATA[");
		sb.append(getRequestedEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestedTotalHours</column-name><column-value><![CDATA[");
		sb.append(getRequestedTotalHours());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>promoteTrip</column-name><column-value><![CDATA[");
		sb.append(getPromoteTrip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>confirmedStartDate</column-name><column-value><![CDATA[");
		sb.append(getConfirmedStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>confirmedEndDate</column-name><column-value><![CDATA[");
		sb.append(getConfirmedEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>confirmedTotalHours</column-name><column-value><![CDATA[");
		sb.append(getConfirmedTotalHours());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactBenefit</column-name><column-value><![CDATA[");
		sb.append(getContactBenefit());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactComments</column-name><column-value><![CDATA[");
		sb.append(getContactComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hash</column-name><column-value><![CDATA[");
		sb.append(getHash());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>feedbackDescription</column-name><column-value><![CDATA[");
		sb.append(getFeedbackDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeBenefit</column-name><column-value><![CDATA[");
		sb.append(getEmployeeBenefit());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>recipientBenefit</column-name><column-value><![CDATA[");
		sb.append(getRecipientBenefit());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shareStory</column-name><column-value><![CDATA[");
		sb.append(getShareStory());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EVPServiceRequest.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EVPServiceRequest.class
		};
	private long _evpServiceRequestId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _contactEmailAddressId;
	private long _contactPhoneId;
	private long _contactUserId;
	private String _contactUserUuid;
	private long _evpRequestOrganizationId;
	private long _managerUserId;
	private String _managerUserUuid;
	private long _parentEVPServiceRequestId;
	private long _requestOrganizationAddressId;
	private long _requestOrganizationWebsiteId;
	private long _subsidiaryGroupId;
	private String _description;
	private int _employmentType;
	private int _employmentHoursPerWeek;
	private String _purpose;
	private String _purposeOther;
	private String _behalfOf;
	private String _behalfOfOther;
	private Date _requestedStartDate;
	private Date _requestedEndDate;
	private int _requestedTotalHours;
	private boolean _promoteTrip;
	private Date _confirmedStartDate;
	private Date _confirmedEndDate;
	private int _confirmedTotalHours;
	private String _contactBenefit;
	private String _contactComments;
	private String _hash;
	private String _feedbackDescription;
	private String _employeeBenefit;
	private String _recipientBenefit;
	private boolean _shareStory;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserUuid;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private EVPServiceRequest _escapedModel;
}